# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""
This module defines internals of BLPAPI-Py and the following classes:
- CorrelationId: a key to track requests and subscriptions

Copyright 2012. Bloomberg Finance L.P.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to
deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:  The above
copyright notice and this permission notice shall be included in all copies
or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
"""


from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_internals')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_internals')
    _internals = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_internals', [dirname(__file__)])
        except ImportError:
            import _internals
            return _internals
        try:
            _mod = imp.load_module('_internals', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _internals = swig_import_helper()
    del swig_import_helper
else:
    import _internals
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

TOPICLIST_NOT_CREATED = _internals.TOPICLIST_NOT_CREATED
TOPICLIST_CREATED = _internals.TOPICLIST_CREATED
TOPICLIST_FAILURE = _internals.TOPICLIST_FAILURE
RESOLUTIONLIST_UNRESOLVED = _internals.RESOLUTIONLIST_UNRESOLVED
RESOLUTIONLIST_RESOLVED = _internals.RESOLUTIONLIST_RESOLVED
RESOLUTIONLIST_RESOLUTION_FAILURE_BAD_SERVICE = _internals.RESOLUTIONLIST_RESOLUTION_FAILURE_BAD_SERVICE
RESOLUTIONLIST_RESOLUTION_FAILURE_SERVICE_AUTHORIZATION_FAILED = _internals.RESOLUTIONLIST_RESOLUTION_FAILURE_SERVICE_AUTHORIZATION_FAILED
RESOLUTIONLIST_RESOLUTION_FAILURE_BAD_TOPIC = _internals.RESOLUTIONLIST_RESOLUTION_FAILURE_BAD_TOPIC
RESOLUTIONLIST_RESOLUTION_FAILURE_TOPIC_AUTHORIZATION_FAILED = _internals.RESOLUTIONLIST_RESOLUTION_FAILURE_TOPIC_AUTHORIZATION_FAILED
MESSAGE_FRAGMENT_NONE = _internals.MESSAGE_FRAGMENT_NONE
MESSAGE_FRAGMENT_START = _internals.MESSAGE_FRAGMENT_START
MESSAGE_FRAGMENT_INTERMEDIATE = _internals.MESSAGE_FRAGMENT_INTERMEDIATE
MESSAGE_FRAGMENT_END = _internals.MESSAGE_FRAGMENT_END
ELEMENTDEFINITION_UNBOUNDED = _internals.ELEMENTDEFINITION_UNBOUNDED
ELEMENT_INDEX_END = _internals.ELEMENT_INDEX_END
SERVICEREGISTRATIONOPTIONS_PRIORITY_MEDIUM = _internals.SERVICEREGISTRATIONOPTIONS_PRIORITY_MEDIUM
SERVICEREGISTRATIONOPTIONS_PRIORITY_HIGH = _internals.SERVICEREGISTRATIONOPTIONS_PRIORITY_HIGH
CORRELATION_TYPE_UNSET = _internals.CORRELATION_TYPE_UNSET
CORRELATION_TYPE_INT = _internals.CORRELATION_TYPE_INT
CORRELATION_TYPE_POINTER = _internals.CORRELATION_TYPE_POINTER
CORRELATION_TYPE_AUTOGEN = _internals.CORRELATION_TYPE_AUTOGEN
CORRELATION_MAX_CLASS_ID = _internals.CORRELATION_MAX_CLASS_ID
MANAGEDPTR_COPY = _internals.MANAGEDPTR_COPY
MANAGEDPTR_DESTROY = _internals.MANAGEDPTR_DESTROY
DATETIME_YEAR_PART = _internals.DATETIME_YEAR_PART
DATETIME_MONTH_PART = _internals.DATETIME_MONTH_PART
DATETIME_DAY_PART = _internals.DATETIME_DAY_PART
DATETIME_OFFSET_PART = _internals.DATETIME_OFFSET_PART
DATETIME_HOURS_PART = _internals.DATETIME_HOURS_PART
DATETIME_MINUTES_PART = _internals.DATETIME_MINUTES_PART
DATETIME_SECONDS_PART = _internals.DATETIME_SECONDS_PART
DATETIME_MILLISECONDS_PART = _internals.DATETIME_MILLISECONDS_PART
DATETIME_FRACSECONDS_PART = _internals.DATETIME_FRACSECONDS_PART
DATETIME_DATE_PART = _internals.DATETIME_DATE_PART
DATETIME_TIME_PART = _internals.DATETIME_TIME_PART
DATETIME_TIMEMILLI_PART = _internals.DATETIME_TIMEMILLI_PART
DATETIME_TIMEFRACSECONDS_PART = _internals.DATETIME_TIMEFRACSECONDS_PART
EVENTTYPE_ADMIN = _internals.EVENTTYPE_ADMIN
EVENTTYPE_SESSION_STATUS = _internals.EVENTTYPE_SESSION_STATUS
EVENTTYPE_SUBSCRIPTION_STATUS = _internals.EVENTTYPE_SUBSCRIPTION_STATUS
EVENTTYPE_REQUEST_STATUS = _internals.EVENTTYPE_REQUEST_STATUS
EVENTTYPE_RESPONSE = _internals.EVENTTYPE_RESPONSE
EVENTTYPE_PARTIAL_RESPONSE = _internals.EVENTTYPE_PARTIAL_RESPONSE
EVENTTYPE_SUBSCRIPTION_DATA = _internals.EVENTTYPE_SUBSCRIPTION_DATA
EVENTTYPE_SERVICE_STATUS = _internals.EVENTTYPE_SERVICE_STATUS
EVENTTYPE_TIMEOUT = _internals.EVENTTYPE_TIMEOUT
EVENTTYPE_AUTHORIZATION_STATUS = _internals.EVENTTYPE_AUTHORIZATION_STATUS
EVENTTYPE_RESOLUTION_STATUS = _internals.EVENTTYPE_RESOLUTION_STATUS
EVENTTYPE_TOPIC_STATUS = _internals.EVENTTYPE_TOPIC_STATUS
EVENTTYPE_TOKEN_STATUS = _internals.EVENTTYPE_TOKEN_STATUS
EVENTTYPE_REQUEST = _internals.EVENTTYPE_REQUEST
STATUS_ACTIVE = _internals.STATUS_ACTIVE
STATUS_DEPRECATED = _internals.STATUS_DEPRECATED
STATUS_INACTIVE = _internals.STATUS_INACTIVE
STATUS_PENDING_DEPRECATION = _internals.STATUS_PENDING_DEPRECATION
SUBSCRIPTIONSTATUS_UNSUBSCRIBED = _internals.SUBSCRIPTIONSTATUS_UNSUBSCRIBED
SUBSCRIPTIONSTATUS_SUBSCRIBING = _internals.SUBSCRIPTIONSTATUS_SUBSCRIBING
SUBSCRIPTIONSTATUS_SUBSCRIBED = _internals.SUBSCRIPTIONSTATUS_SUBSCRIBED
SUBSCRIPTIONSTATUS_CANCELLED = _internals.SUBSCRIPTIONSTATUS_CANCELLED
SUBSCRIPTIONSTATUS_PENDING_CANCELLATION = _internals.SUBSCRIPTIONSTATUS_PENDING_CANCELLATION
CLIENTMODE_AUTO = _internals.CLIENTMODE_AUTO
CLIENTMODE_DAPI = _internals.CLIENTMODE_DAPI
CLIENTMODE_SAPI = _internals.CLIENTMODE_SAPI
CLIENTMODE_COMPAT_33X = _internals.CLIENTMODE_COMPAT_33X
RESOLVEMODE_DONT_REGISTER_SERVICES = _internals.RESOLVEMODE_DONT_REGISTER_SERVICES
RESOLVEMODE_AUTO_REGISTER_SERVICES = _internals.RESOLVEMODE_AUTO_REGISTER_SERVICES
SEATTYPE_INVALID_SEAT = _internals.SEATTYPE_INVALID_SEAT
SEATTYPE_BPS = _internals.SEATTYPE_BPS
SEATTYPE_NONBPS = _internals.SEATTYPE_NONBPS
SERVICEREGISTRATIONOPTIONS_PRIORITY_LOW = _internals.SERVICEREGISTRATIONOPTIONS_PRIORITY_LOW
REGISTRATIONPARTS_DEFAULT = _internals.REGISTRATIONPARTS_DEFAULT
REGISTRATIONPARTS_PUBLISHING = _internals.REGISTRATIONPARTS_PUBLISHING
REGISTRATIONPARTS_OPERATIONS = _internals.REGISTRATIONPARTS_OPERATIONS
REGISTRATIONPARTS_SUBSCRIBER_RESOLUTION = _internals.REGISTRATIONPARTS_SUBSCRIBER_RESOLUTION
REGISTRATIONPARTS_PUBLISHER_RESOLUTION = _internals.REGISTRATIONPARTS_PUBLISHER_RESOLUTION
DATATYPE_BOOL = _internals.DATATYPE_BOOL
DATATYPE_CHAR = _internals.DATATYPE_CHAR
DATATYPE_BYTE = _internals.DATATYPE_BYTE
DATATYPE_INT32 = _internals.DATATYPE_INT32
DATATYPE_INT64 = _internals.DATATYPE_INT64
DATATYPE_FLOAT32 = _internals.DATATYPE_FLOAT32
DATATYPE_FLOAT64 = _internals.DATATYPE_FLOAT64
DATATYPE_STRING = _internals.DATATYPE_STRING
DATATYPE_BYTEARRAY = _internals.DATATYPE_BYTEARRAY
DATATYPE_DATE = _internals.DATATYPE_DATE
DATATYPE_TIME = _internals.DATATYPE_TIME
DATATYPE_DECIMAL = _internals.DATATYPE_DECIMAL
DATATYPE_DATETIME = _internals.DATATYPE_DATETIME
DATATYPE_ENUMERATION = _internals.DATATYPE_ENUMERATION
DATATYPE_SEQUENCE = _internals.DATATYPE_SEQUENCE
DATATYPE_CHOICE = _internals.DATATYPE_CHOICE
DATATYPE_CORRELATION_ID = _internals.DATATYPE_CORRELATION_ID
blpapi_Logging_SEVERITY_OFF = _internals.blpapi_Logging_SEVERITY_OFF
blpapi_Logging_SEVERITY_FATAL = _internals.blpapi_Logging_SEVERITY_FATAL
blpapi_Logging_SEVERITY_ERROR = _internals.blpapi_Logging_SEVERITY_ERROR
blpapi_Logging_SEVERITY_WARN = _internals.blpapi_Logging_SEVERITY_WARN
blpapi_Logging_SEVERITY_INFO = _internals.blpapi_Logging_SEVERITY_INFO
blpapi_Logging_SEVERITY_DEBUG = _internals.blpapi_Logging_SEVERITY_DEBUG
blpapi_Logging_SEVERITY_TRACE = _internals.blpapi_Logging_SEVERITY_TRACE

def setLoggerCallbackWrapper(cb, severity):
    return _internals.setLoggerCallbackWrapper(cb, severity)
setLoggerCallbackWrapper = _internals.setLoggerCallbackWrapper

def blpapi_Logging_registerCallback(callback, thresholdSeverity):
    return _internals.blpapi_Logging_registerCallback(callback, thresholdSeverity)
blpapi_Logging_registerCallback = _internals.blpapi_Logging_registerCallback

def blpapi_Logging_logTestMessage(severity):
    return _internals.blpapi_Logging_logTestMessage(severity)
blpapi_Logging_logTestMessage = _internals.blpapi_Logging_logTestMessage

def blpapi_DiagnosticsUtil_memoryInfo_wrapper():
    return _internals.blpapi_DiagnosticsUtil_memoryInfo_wrapper()
blpapi_DiagnosticsUtil_memoryInfo_wrapper = _internals.blpapi_DiagnosticsUtil_memoryInfo_wrapper

def blpapi_Message_timeReceived_wrapper(message):
    return _internals.blpapi_Message_timeReceived_wrapper(message)
blpapi_Message_timeReceived_wrapper = _internals.blpapi_Message_timeReceived_wrapper

def blpapi_HighResolutionClock_now_wrapper():
    return _internals.blpapi_HighResolutionClock_now_wrapper()
blpapi_HighResolutionClock_now_wrapper = _internals.blpapi_HighResolutionClock_now_wrapper

def blpapi_Service_printHelper(service, level, spacesPerLevel):
    return _internals.blpapi_Service_printHelper(service, level, spacesPerLevel)
blpapi_Service_printHelper = _internals.blpapi_Service_printHelper

def blpapi_SchemaElementDefinition_printHelper(item, level, spacesPerLevel):
    return _internals.blpapi_SchemaElementDefinition_printHelper(item, level, spacesPerLevel)
blpapi_SchemaElementDefinition_printHelper = _internals.blpapi_SchemaElementDefinition_printHelper

def blpapi_SchemaTypeDefinition_printHelper(item, level, spacesPerLevel):
    return _internals.blpapi_SchemaTypeDefinition_printHelper(item, level, spacesPerLevel)
blpapi_SchemaTypeDefinition_printHelper = _internals.blpapi_SchemaTypeDefinition_printHelper

def blpapi_SchemaTypeDefinition_hasElementDefinition(type, nameString, name):
    return _internals.blpapi_SchemaTypeDefinition_hasElementDefinition(type, nameString, name)
blpapi_SchemaTypeDefinition_hasElementDefinition = _internals.blpapi_SchemaTypeDefinition_hasElementDefinition

def blpapi_ConstantList_hasConstant(list, nameString, name):
    return _internals.blpapi_ConstantList_hasConstant(list, nameString, name)
blpapi_ConstantList_hasConstant = _internals.blpapi_ConstantList_hasConstant

def blpapi_Service_hasEventDefinition(service, nameString, name):
    return _internals.blpapi_Service_hasEventDefinition(service, nameString, name)
blpapi_Service_hasEventDefinition = _internals.blpapi_Service_hasEventDefinition

def blpapi_Service_hasOperation(service, nameString, name):
    return _internals.blpapi_Service_hasOperation(service, nameString, name)
blpapi_Service_hasOperation = _internals.blpapi_Service_hasOperation

def blpapi_SubscriptionList_addHelper(list, topic, correlationId, fields, options):
    return _internals.blpapi_SubscriptionList_addHelper(list, topic, correlationId, fields, options)
blpapi_SubscriptionList_addHelper = _internals.blpapi_SubscriptionList_addHelper

def blpapi_Name_hasName(nameString):
    return _internals.blpapi_Name_hasName(nameString)
blpapi_Name_hasName = _internals.blpapi_Name_hasName

def blpapi_TopicList_createFromResolutionList(arg1):
    return _internals.blpapi_TopicList_createFromResolutionList(arg1)
blpapi_TopicList_createFromResolutionList = _internals.blpapi_TopicList_createFromResolutionList
class intArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _internals.new_intArray(nelements)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _internals.delete_intArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _internals.intArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _internals.intArray___setitem__(self, index, value)

    def cast(self):
        return _internals.intArray_cast(self)
    if _newclass:
        frompointer = staticmethod(_internals.intArray_frompointer)
    else:
        frompointer = _internals.intArray_frompointer
intArray_swigregister = _internals.intArray_swigregister
intArray_swigregister(intArray)

def intArray_frompointer(t):
    return _internals.intArray_frompointer(t)
intArray_frompointer = _internals.intArray_frompointer


def new_topicPtrArray(nelements):
    return _internals.new_topicPtrArray(nelements)
new_topicPtrArray = _internals.new_topicPtrArray

def delete_topicPtrArray(ary):
    return _internals.delete_topicPtrArray(ary)
delete_topicPtrArray = _internals.delete_topicPtrArray

def topicPtrArray_getitem(ary, index):
    return _internals.topicPtrArray_getitem(ary, index)
topicPtrArray_getitem = _internals.topicPtrArray_getitem

def topicPtrArray_setitem(ary, index, value):
    return _internals.topicPtrArray_setitem(ary, index, value)
topicPtrArray_setitem = _internals.topicPtrArray_setitem

def CorrelationId_t_equals(cid1, cid2):
    return _internals.CorrelationId_t_equals(cid1, cid2)
CorrelationId_t_equals = _internals.CorrelationId_t_equals
class CorrelationId(_object):
    """
    A key used to identify individual subscriptions or requests.

    CorrelationId([value[, classId=0]]) constructs a CorrelationId object.
    If 'value' is integer (either int or long) then created CorrelationId will have
    type() == CorrelationId.INT_TYPE. Otherwise it will have
    type() == CorrelationId.OBJECT_TYPE. If no arguments are specified
    then it will have type() == CorrelationId.UNSET_TYPE.

    Two CorrelationIds are considered equal if they have the same
    type() and:
    - holds the same (not just equal!) objects in case of
        type() == CorrelationId.OBJECT_TYPE
    - holds equal integers in case of
        type() == CorrelationId.INT_TYPE or
        type() == CorrelationId.AUTOGEN_TYPE
    - True otherwise
        (i.e. in case of type() == CorrelationId.UNSET_TYPE)

    It is possible that an user constructed CorrelationId and a
    CorrelationId generated by the API could return the same
    result for value(). However, they will not compare equal because
    they have different type().

    CorrelationId objects are passed to many of the Session object
    methods which initiate an asynchronous operations and are
    obtained from Message objects which are delivered as a result
    of those asynchronous operations.

    When subscribing or requesting information an application has
    the choice of providing a CorrelationId they construct
    themselves or allowing the session to construct one for
    them. If the application supplies a CorrelationId it must not
    re-use the value contained in it in another CorrelationId
    whilst the original request or subscription is still active.

    Class attributes:
        Possible return values for type() method:
            UNSET_TYPE      The CorrelationId is unset. That is, it was created by
                            the default CorrelationId constructor.
            INT_TYPE        The CorrelationId was created from an integer (or long)
                            supplied by the user.
            OBJECT_TYPE     The CorrelationId was created from an object supplied by
                            the user.
            AUTOGEN_TYPE    The CorrelationId was created internally by API.

        MAX_CLASS_ID    The maximum value allowed for classId.
    """

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CorrelationId, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CorrelationId, name)
    __repr__ = _swig_repr

    UNSET_TYPE = _internals.CORRELATION_TYPE_UNSET

    INT_TYPE = _internals.CORRELATION_TYPE_INT

    OBJECT_TYPE = _internals.CORRELATION_TYPE_POINTER

    AUTOGEN_TYPE = _internals.CORRELATION_TYPE_AUTOGEN

    MAX_CLASS_ID = _internals.CORRELATION_MAX_CLASS_ID

    __TYPE_NAMES = {
        _internals.CORRELATION_TYPE_UNSET: "UNSET",
        _internals.CORRELATION_TYPE_INT: "INTEGER",
        _internals.CORRELATION_TYPE_POINTER: "OBJECT",
        _internals.CORRELATION_TYPE_AUTOGEN: "AUTOGEN"
    }

    def __str__(self):
        """x.__str__() <==> str(x)"""
        valueType = self.type()
        valueTypeName = CorrelationId.__TYPE_NAMES[valueType] 

        if valueType == CorrelationId.UNSET_TYPE:
            return valueTypeName
        else:
            return "({0}: {1!r}, ClassId: {2})".format(
                valueTypeName, self.value(), self.classId())

    def __hash__(self):
        return hash((self.type(), self.classId(), self.__toInteger()))

    def __eq__(self, other):
        """x.__eq__(y) <==> x==y"""
        try:
            return CorrelationId_t_equals(self, other)
        except Exception:
            return NotImplemented

    def __ne__(self, other):
        """x.__ne__(y) <==> x!=y"""
        equal = self.__eq__(other)
        return NotImplemented if equal is NotImplemented else not equal

    def value(self):
        """Return the value of this CorrelationId object. The return value
        depends on this CorrelationId's value type and could be:
            - integer (type() == CorrelationId.INT_TYPE
                or type() == CorrelationId.AUTOGEN_TYPE)
            - object (type() == CorrelationId.OBJECT_TYPE)
            - None (type() == CorrelationId.UNSET_TYPE)
        """
        valueType = self.type()
        if valueType == CorrelationId.INT_TYPE \
                or valueType == CorrelationId.AUTOGEN_TYPE:
            return self.__asInteger()
        elif valueType == CorrelationId.OBJECT_TYPE:
            return self.__asObject()
        else:
            return None

    def _handle(self):
        return self


    def __init__(self, *args):
        """
        A key used to identify individual subscriptions or requests.

        CorrelationId([value[, classId=0]]) constructs a CorrelationId object.
        If 'value' is integer (either int or long) then created CorrelationId will have
        type() == CorrelationId.INT_TYPE. Otherwise it will have
        type() == CorrelationId.OBJECT_TYPE. If no arguments are specified
        then it will have type() == CorrelationId.UNSET_TYPE.

        Two CorrelationIds are considered equal if they have the same
        type() and:
        - holds the same (not just equal!) objects in case of
            type() == CorrelationId.OBJECT_TYPE
        - holds equal integers in case of
            type() == CorrelationId.INT_TYPE or
            type() == CorrelationId.AUTOGEN_TYPE
        - True otherwise
            (i.e. in case of type() == CorrelationId.UNSET_TYPE)

        It is possible that an user constructed CorrelationId and a
        CorrelationId generated by the API could return the same
        result for value(). However, they will not compare equal because
        they have different type().

        CorrelationId objects are passed to many of the Session object
        methods which initiate an asynchronous operations and are
        obtained from Message objects which are delivered as a result
        of those asynchronous operations.

        When subscribing or requesting information an application has
        the choice of providing a CorrelationId they construct
        themselves or allowing the session to construct one for
        them. If the application supplies a CorrelationId it must not
        re-use the value contained in it in another CorrelationId
        whilst the original request or subscription is still active.

        Class attributes:
            Possible return values for type() method:
                UNSET_TYPE      The CorrelationId is unset. That is, it was created by
                                the default CorrelationId constructor.
                INT_TYPE        The CorrelationId was created from an integer (or long)
                                supplied by the user.
                OBJECT_TYPE     The CorrelationId was created from an object supplied by
                                the user.
                AUTOGEN_TYPE    The CorrelationId was created internally by API.

            MAX_CLASS_ID    The maximum value allowed for classId.
        """
        this = _internals.new_CorrelationId(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _internals.delete_CorrelationId
    __del__ = lambda self: None

    def type(self):
        """Return the type of this CorrelationId object (see xxx_TYPE class attributes)"""
        return _internals.CorrelationId_type(self)


    def classId(self):
        """Return the user defined classification of this CorrelationId object"""
        return _internals.CorrelationId_classId(self)


    def __asObject(self):
        return _internals.CorrelationId___asObject(self)

    def __asInteger(self):
        return _internals.CorrelationId___asInteger(self)

    def __toInteger(self):
        return _internals.CorrelationId___toInteger(self)
CorrelationId_swigregister = _internals.CorrelationId_swigregister
CorrelationId_swigregister(CorrelationId)


def blpapi_Element_setElementFloat(element, nameString, name, value):
    return _internals.blpapi_Element_setElementFloat(element, nameString, name, value)
blpapi_Element_setElementFloat = _internals.blpapi_Element_setElementFloat

def blpapi_Element_setValueFloat(element, value, index):
    return _internals.blpapi_Element_setValueFloat(element, value, index)
blpapi_Element_setValueFloat = _internals.blpapi_Element_setValueFloat

def blpapi_Element_printHelper(element, level, spacesPerLevel):
    return _internals.blpapi_Element_printHelper(element, level, spacesPerLevel)
blpapi_Element_printHelper = _internals.blpapi_Element_printHelper

def blpapi_Element_name(element):
    return _internals.blpapi_Element_name(element)
blpapi_Element_name = _internals.blpapi_Element_name

def blpapi_Element_nameString(element):
    return _internals.blpapi_Element_nameString(element)
blpapi_Element_nameString = _internals.blpapi_Element_nameString

def blpapi_Element_definition(element):
    return _internals.blpapi_Element_definition(element)
blpapi_Element_definition = _internals.blpapi_Element_definition

def blpapi_Element_datatype(element):
    return _internals.blpapi_Element_datatype(element)
blpapi_Element_datatype = _internals.blpapi_Element_datatype

def blpapi_Element_isComplexType(element):
    return _internals.blpapi_Element_isComplexType(element)
blpapi_Element_isComplexType = _internals.blpapi_Element_isComplexType

def blpapi_Element_isArray(element):
    return _internals.blpapi_Element_isArray(element)
blpapi_Element_isArray = _internals.blpapi_Element_isArray

def blpapi_Element_isReadOnly(element):
    return _internals.blpapi_Element_isReadOnly(element)
blpapi_Element_isReadOnly = _internals.blpapi_Element_isReadOnly

def blpapi_Element_numValues(element):
    return _internals.blpapi_Element_numValues(element)
blpapi_Element_numValues = _internals.blpapi_Element_numValues

def blpapi_Element_numElements(element):
    return _internals.blpapi_Element_numElements(element)
blpapi_Element_numElements = _internals.blpapi_Element_numElements

def blpapi_Element_isNullValue(element, position):
    return _internals.blpapi_Element_isNullValue(element, position)
blpapi_Element_isNullValue = _internals.blpapi_Element_isNullValue

def blpapi_Element_isNull(element):
    return _internals.blpapi_Element_isNull(element)
blpapi_Element_isNull = _internals.blpapi_Element_isNull

def blpapi_Element_getElementAt(element, position):
    return _internals.blpapi_Element_getElementAt(element, position)
blpapi_Element_getElementAt = _internals.blpapi_Element_getElementAt

def blpapi_Element_getElement(element, nameString, name):
    return _internals.blpapi_Element_getElement(element, nameString, name)
blpapi_Element_getElement = _internals.blpapi_Element_getElement

def blpapi_Element_hasElementEx(element, nameString, name, excludeNullElements, reserved):
    return _internals.blpapi_Element_hasElementEx(element, nameString, name, excludeNullElements, reserved)
blpapi_Element_hasElementEx = _internals.blpapi_Element_hasElementEx

def blpapi_Element_getValueAsBool(element, index):
    return _internals.blpapi_Element_getValueAsBool(element, index)
blpapi_Element_getValueAsBool = _internals.blpapi_Element_getValueAsBool

def blpapi_Element_getValueAsChar(element, buffer, index):
    return _internals.blpapi_Element_getValueAsChar(element, buffer, index)
blpapi_Element_getValueAsChar = _internals.blpapi_Element_getValueAsChar

def blpapi_Element_getValueAsInt32(element, buffer, index):
    return _internals.blpapi_Element_getValueAsInt32(element, buffer, index)
blpapi_Element_getValueAsInt32 = _internals.blpapi_Element_getValueAsInt32

def blpapi_Element_getValueAsInt64(element, index):
    return _internals.blpapi_Element_getValueAsInt64(element, index)
blpapi_Element_getValueAsInt64 = _internals.blpapi_Element_getValueAsInt64

def blpapi_Element_getValueAsFloat64(element, index):
    return _internals.blpapi_Element_getValueAsFloat64(element, index)
blpapi_Element_getValueAsFloat64 = _internals.blpapi_Element_getValueAsFloat64

def blpapi_Element_getValueAsString(element, index):
    return _internals.blpapi_Element_getValueAsString(element, index)
blpapi_Element_getValueAsString = _internals.blpapi_Element_getValueAsString

def blpapi_Element_getValueAsDatetime(element, index):
    return _internals.blpapi_Element_getValueAsDatetime(element, index)
blpapi_Element_getValueAsDatetime = _internals.blpapi_Element_getValueAsDatetime

def blpapi_Element_getValueAsHighPrecisionDatetime(element, buffer, index):
    return _internals.blpapi_Element_getValueAsHighPrecisionDatetime(element, buffer, index)
blpapi_Element_getValueAsHighPrecisionDatetime = _internals.blpapi_Element_getValueAsHighPrecisionDatetime

def blpapi_Element_getValueAsElement(element, index):
    return _internals.blpapi_Element_getValueAsElement(element, index)
blpapi_Element_getValueAsElement = _internals.blpapi_Element_getValueAsElement

def blpapi_Element_getValueAsName(element, index):
    return _internals.blpapi_Element_getValueAsName(element, index)
blpapi_Element_getValueAsName = _internals.blpapi_Element_getValueAsName

def blpapi_Element_getChoice(element):
    return _internals.blpapi_Element_getChoice(element)
blpapi_Element_getChoice = _internals.blpapi_Element_getChoice

def blpapi_Element_setValueBool(element, value, index):
    return _internals.blpapi_Element_setValueBool(element, value, index)
blpapi_Element_setValueBool = _internals.blpapi_Element_setValueBool

def blpapi_Element_setValueInt32(element, value, index):
    return _internals.blpapi_Element_setValueInt32(element, value, index)
blpapi_Element_setValueInt32 = _internals.blpapi_Element_setValueInt32

def blpapi_Element_setValueInt64(element, value, index):
    return _internals.blpapi_Element_setValueInt64(element, value, index)
blpapi_Element_setValueInt64 = _internals.blpapi_Element_setValueInt64

def blpapi_Element_setValueString(element, value, index):
    return _internals.blpapi_Element_setValueString(element, value, index)
blpapi_Element_setValueString = _internals.blpapi_Element_setValueString

def blpapi_Element_setValueDatetime(element, value, index):
    return _internals.blpapi_Element_setValueDatetime(element, value, index)
blpapi_Element_setValueDatetime = _internals.blpapi_Element_setValueDatetime

def blpapi_Element_setValueHighPrecisionDatetime(element, value, index):
    return _internals.blpapi_Element_setValueHighPrecisionDatetime(element, value, index)
blpapi_Element_setValueHighPrecisionDatetime = _internals.blpapi_Element_setValueHighPrecisionDatetime

def blpapi_Element_setValueFromName(element, value, index):
    return _internals.blpapi_Element_setValueFromName(element, value, index)
blpapi_Element_setValueFromName = _internals.blpapi_Element_setValueFromName

def blpapi_Element_setElementBool(element, nameString, name, value):
    return _internals.blpapi_Element_setElementBool(element, nameString, name, value)
blpapi_Element_setElementBool = _internals.blpapi_Element_setElementBool

def blpapi_Element_setElementInt32(element, nameString, name, value):
    return _internals.blpapi_Element_setElementInt32(element, nameString, name, value)
blpapi_Element_setElementInt32 = _internals.blpapi_Element_setElementInt32

def blpapi_Element_setElementInt64(element, nameString, name, value):
    return _internals.blpapi_Element_setElementInt64(element, nameString, name, value)
blpapi_Element_setElementInt64 = _internals.blpapi_Element_setElementInt64

def blpapi_Element_setElementString(element, nameString, name, value):
    return _internals.blpapi_Element_setElementString(element, nameString, name, value)
blpapi_Element_setElementString = _internals.blpapi_Element_setElementString

def blpapi_Element_setElementDatetime(element, nameString, name, value):
    return _internals.blpapi_Element_setElementDatetime(element, nameString, name, value)
blpapi_Element_setElementDatetime = _internals.blpapi_Element_setElementDatetime

def blpapi_Element_setElementHighPrecisionDatetime(element, nameString, name, value):
    return _internals.blpapi_Element_setElementHighPrecisionDatetime(element, nameString, name, value)
blpapi_Element_setElementHighPrecisionDatetime = _internals.blpapi_Element_setElementHighPrecisionDatetime

def blpapi_Element_setElementFromName(element, elementName, name, buffer):
    return _internals.blpapi_Element_setElementFromName(element, elementName, name, buffer)
blpapi_Element_setElementFromName = _internals.blpapi_Element_setElementFromName

def blpapi_Element_appendElement(element):
    return _internals.blpapi_Element_appendElement(element)
blpapi_Element_appendElement = _internals.blpapi_Element_appendElement

def blpapi_Element_setChoice(element, nameCstr, name, index):
    return _internals.blpapi_Element_setChoice(element, nameCstr, name, index)
blpapi_Element_setChoice = _internals.blpapi_Element_setChoice

def blpapi_EventFormatter_setValueFloat(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueFloat(formatter, typeString, typeName, value)
blpapi_EventFormatter_setValueFloat = _internals.blpapi_EventFormatter_setValueFloat

def blpapi_EventFormatter_appendValueFloat(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueFloat(formatter, value)
blpapi_EventFormatter_appendValueFloat = _internals.blpapi_EventFormatter_appendValueFloat

def blpapi_EventFormatter_create(event):
    return _internals.blpapi_EventFormatter_create(event)
blpapi_EventFormatter_create = _internals.blpapi_EventFormatter_create

def blpapi_EventFormatter_destroy(victim):
    return _internals.blpapi_EventFormatter_destroy(victim)
blpapi_EventFormatter_destroy = _internals.blpapi_EventFormatter_destroy

def blpapi_EventFormatter_appendMessage(formatter, typeString, typeName, topic):
    return _internals.blpapi_EventFormatter_appendMessage(formatter, typeString, typeName, topic)
blpapi_EventFormatter_appendMessage = _internals.blpapi_EventFormatter_appendMessage

def blpapi_EventFormatter_appendMessageSeq(formatter, typeString, typeName, topic, sequenceNumber, arg6):
    return _internals.blpapi_EventFormatter_appendMessageSeq(formatter, typeString, typeName, topic, sequenceNumber, arg6)
blpapi_EventFormatter_appendMessageSeq = _internals.blpapi_EventFormatter_appendMessageSeq

def blpapi_EventFormatter_appendResponse(formatter, typeString, typeName):
    return _internals.blpapi_EventFormatter_appendResponse(formatter, typeString, typeName)
blpapi_EventFormatter_appendResponse = _internals.blpapi_EventFormatter_appendResponse

def blpapi_EventFormatter_appendRecapMessage(formatter, topic, cid):
    return _internals.blpapi_EventFormatter_appendRecapMessage(formatter, topic, cid)
blpapi_EventFormatter_appendRecapMessage = _internals.blpapi_EventFormatter_appendRecapMessage

def blpapi_EventFormatter_appendRecapMessageSeq(formatter, topic, cid, sequenceNumber, arg5):
    return _internals.blpapi_EventFormatter_appendRecapMessageSeq(formatter, topic, cid, sequenceNumber, arg5)
blpapi_EventFormatter_appendRecapMessageSeq = _internals.blpapi_EventFormatter_appendRecapMessageSeq

def blpapi_EventFormatter_setValueBool(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueBool(formatter, typeString, typeName, value)
blpapi_EventFormatter_setValueBool = _internals.blpapi_EventFormatter_setValueBool

def blpapi_EventFormatter_setValueChar(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueChar(formatter, typeString, typeName, value)
blpapi_EventFormatter_setValueChar = _internals.blpapi_EventFormatter_setValueChar

def blpapi_EventFormatter_setValueInt32(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueInt32(formatter, typeString, typeName, value)
blpapi_EventFormatter_setValueInt32 = _internals.blpapi_EventFormatter_setValueInt32

def blpapi_EventFormatter_setValueInt64(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueInt64(formatter, typeString, typeName, value)
blpapi_EventFormatter_setValueInt64 = _internals.blpapi_EventFormatter_setValueInt64

def blpapi_EventFormatter_setValueDatetime(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueDatetime(formatter, typeString, typeName, value)
blpapi_EventFormatter_setValueDatetime = _internals.blpapi_EventFormatter_setValueDatetime

def blpapi_EventFormatter_setValueString(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueString(formatter, typeString, typeName, value)
blpapi_EventFormatter_setValueString = _internals.blpapi_EventFormatter_setValueString

def blpapi_EventFormatter_setValueFromName(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueFromName(formatter, typeString, typeName, value)
blpapi_EventFormatter_setValueFromName = _internals.blpapi_EventFormatter_setValueFromName

def blpapi_EventFormatter_setValueNull(formatter, typeString, typeName):
    return _internals.blpapi_EventFormatter_setValueNull(formatter, typeString, typeName)
blpapi_EventFormatter_setValueNull = _internals.blpapi_EventFormatter_setValueNull

def blpapi_EventFormatter_pushElement(formatter, typeString, typeName):
    return _internals.blpapi_EventFormatter_pushElement(formatter, typeString, typeName)
blpapi_EventFormatter_pushElement = _internals.blpapi_EventFormatter_pushElement

def blpapi_EventFormatter_popElement(formatter):
    return _internals.blpapi_EventFormatter_popElement(formatter)
blpapi_EventFormatter_popElement = _internals.blpapi_EventFormatter_popElement

def blpapi_EventFormatter_appendValueBool(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueBool(formatter, value)
blpapi_EventFormatter_appendValueBool = _internals.blpapi_EventFormatter_appendValueBool

def blpapi_EventFormatter_appendValueChar(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueChar(formatter, value)
blpapi_EventFormatter_appendValueChar = _internals.blpapi_EventFormatter_appendValueChar

def blpapi_EventFormatter_appendValueInt32(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueInt32(formatter, value)
blpapi_EventFormatter_appendValueInt32 = _internals.blpapi_EventFormatter_appendValueInt32

def blpapi_EventFormatter_appendValueInt64(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueInt64(formatter, value)
blpapi_EventFormatter_appendValueInt64 = _internals.blpapi_EventFormatter_appendValueInt64

def blpapi_EventFormatter_appendValueDatetime(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueDatetime(formatter, value)
blpapi_EventFormatter_appendValueDatetime = _internals.blpapi_EventFormatter_appendValueDatetime

def blpapi_EventFormatter_appendValueString(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueString(formatter, value)
blpapi_EventFormatter_appendValueString = _internals.blpapi_EventFormatter_appendValueString

def blpapi_EventFormatter_appendValueFromName(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueFromName(formatter, value)
blpapi_EventFormatter_appendValueFromName = _internals.blpapi_EventFormatter_appendValueFromName

def blpapi_EventFormatter_appendElement(formatter):
    return _internals.blpapi_EventFormatter_appendElement(formatter)
blpapi_EventFormatter_appendElement = _internals.blpapi_EventFormatter_appendElement

def Session_createHelper(parameters, eventHandlerFunc, dispatcher):
    return _internals.Session_createHelper(parameters, eventHandlerFunc, dispatcher)
Session_createHelper = _internals.Session_createHelper

def Session_destroyHelper(sessionHandle, eventHandlerFunc):
    return _internals.Session_destroyHelper(sessionHandle, eventHandlerFunc)
Session_destroyHelper = _internals.Session_destroyHelper

def blpapi_EventDispatcher_create(numDispatcherThreads):
    return _internals.blpapi_EventDispatcher_create(numDispatcherThreads)
blpapi_EventDispatcher_create = _internals.blpapi_EventDispatcher_create

def blpapi_EventDispatcher_destroy(handle):
    return _internals.blpapi_EventDispatcher_destroy(handle)
blpapi_EventDispatcher_destroy = _internals.blpapi_EventDispatcher_destroy

def blpapi_EventDispatcher_start(handle):
    return _internals.blpapi_EventDispatcher_start(handle)
blpapi_EventDispatcher_start = _internals.blpapi_EventDispatcher_start

def blpapi_EventDispatcher_stop(handle, async):
    return _internals.blpapi_EventDispatcher_stop(handle, async)
blpapi_EventDispatcher_stop = _internals.blpapi_EventDispatcher_stop

def ProviderSession_createHelper(parameters, eventHandlerFunc, dispatcher):
    return _internals.ProviderSession_createHelper(parameters, eventHandlerFunc, dispatcher)
ProviderSession_createHelper = _internals.ProviderSession_createHelper

def ProviderSession_destroyHelper(sessionHandle, eventHandlerFunc):
    return _internals.ProviderSession_destroyHelper(sessionHandle, eventHandlerFunc)
ProviderSession_destroyHelper = _internals.ProviderSession_destroyHelper
UNKNOWN_CLASS = _internals.UNKNOWN_CLASS
INVALIDSTATE_CLASS = _internals.INVALIDSTATE_CLASS
INVALIDARG_CLASS = _internals.INVALIDARG_CLASS
IOERROR_CLASS = _internals.IOERROR_CLASS
CNVERROR_CLASS = _internals.CNVERROR_CLASS
BOUNDSERROR_CLASS = _internals.BOUNDSERROR_CLASS
NOTFOUND_CLASS = _internals.NOTFOUND_CLASS
FLDNOTFOUND_CLASS = _internals.FLDNOTFOUND_CLASS
UNSUPPORTED_CLASS = _internals.UNSUPPORTED_CLASS
ERROR_UNKNOWN = _internals.ERROR_UNKNOWN
ERROR_ILLEGAL_ARG = _internals.ERROR_ILLEGAL_ARG
ERROR_ILLEGAL_ACCESS = _internals.ERROR_ILLEGAL_ACCESS
ERROR_INVALID_SESSION = _internals.ERROR_INVALID_SESSION
ERROR_DUPLICATE_CORRELATIONID = _internals.ERROR_DUPLICATE_CORRELATIONID
ERROR_INTERNAL_ERROR = _internals.ERROR_INTERNAL_ERROR
ERROR_RESOLVE_FAILED = _internals.ERROR_RESOLVE_FAILED
ERROR_CONNECT_FAILED = _internals.ERROR_CONNECT_FAILED
ERROR_ILLEGAL_STATE = _internals.ERROR_ILLEGAL_STATE
ERROR_CODEC_FAILURE = _internals.ERROR_CODEC_FAILURE
ERROR_INDEX_OUT_OF_RANGE = _internals.ERROR_INDEX_OUT_OF_RANGE
ERROR_INVALID_CONVERSION = _internals.ERROR_INVALID_CONVERSION
ERROR_ITEM_NOT_FOUND = _internals.ERROR_ITEM_NOT_FOUND
ERROR_IO_ERROR = _internals.ERROR_IO_ERROR
ERROR_CORRELATION_NOT_FOUND = _internals.ERROR_CORRELATION_NOT_FOUND
ERROR_SERVICE_NOT_FOUND = _internals.ERROR_SERVICE_NOT_FOUND
ERROR_LOGON_LOOKUP_FAILED = _internals.ERROR_LOGON_LOOKUP_FAILED
ERROR_DS_LOOKUP_FAILED = _internals.ERROR_DS_LOOKUP_FAILED
ERROR_UNSUPPORTED_OPERATION = _internals.ERROR_UNSUPPORTED_OPERATION
ERROR_DS_PROPERTY_NOT_FOUND = _internals.ERROR_DS_PROPERTY_NOT_FOUND

def blpapi_getLastErrorDescription(resultCode):
    return _internals.blpapi_getLastErrorDescription(resultCode)
blpapi_getLastErrorDescription = _internals.blpapi_getLastErrorDescription

def blpapi_SessionOptions_create():
    return _internals.blpapi_SessionOptions_create()
blpapi_SessionOptions_create = _internals.blpapi_SessionOptions_create

def blpapi_SessionOptions_destroy(parameters):
    return _internals.blpapi_SessionOptions_destroy(parameters)
blpapi_SessionOptions_destroy = _internals.blpapi_SessionOptions_destroy

def blpapi_SessionOptions_setServerHost(parameters, serverHost):
    return _internals.blpapi_SessionOptions_setServerHost(parameters, serverHost)
blpapi_SessionOptions_setServerHost = _internals.blpapi_SessionOptions_setServerHost

def blpapi_SessionOptions_setServerPort(parameters, serverPort):
    return _internals.blpapi_SessionOptions_setServerPort(parameters, serverPort)
blpapi_SessionOptions_setServerPort = _internals.blpapi_SessionOptions_setServerPort

def blpapi_SessionOptions_setServerAddress(parameters, serverHost, serverPort, index):
    return _internals.blpapi_SessionOptions_setServerAddress(parameters, serverHost, serverPort, index)
blpapi_SessionOptions_setServerAddress = _internals.blpapi_SessionOptions_setServerAddress

def blpapi_SessionOptions_removeServerAddress(parameters, index):
    return _internals.blpapi_SessionOptions_removeServerAddress(parameters, index)
blpapi_SessionOptions_removeServerAddress = _internals.blpapi_SessionOptions_removeServerAddress

def blpapi_SessionOptions_setConnectTimeout(parameters, timeoutInMilliseconds):
    return _internals.blpapi_SessionOptions_setConnectTimeout(parameters, timeoutInMilliseconds)
blpapi_SessionOptions_setConnectTimeout = _internals.blpapi_SessionOptions_setConnectTimeout

def blpapi_SessionOptions_setDefaultServices(parameters, defaultServices):
    return _internals.blpapi_SessionOptions_setDefaultServices(parameters, defaultServices)
blpapi_SessionOptions_setDefaultServices = _internals.blpapi_SessionOptions_setDefaultServices

def blpapi_SessionOptions_setDefaultSubscriptionService(parameters, serviceIdentifier):
    return _internals.blpapi_SessionOptions_setDefaultSubscriptionService(parameters, serviceIdentifier)
blpapi_SessionOptions_setDefaultSubscriptionService = _internals.blpapi_SessionOptions_setDefaultSubscriptionService

def blpapi_SessionOptions_setDefaultTopicPrefix(parameters, prefix):
    return _internals.blpapi_SessionOptions_setDefaultTopicPrefix(parameters, prefix)
blpapi_SessionOptions_setDefaultTopicPrefix = _internals.blpapi_SessionOptions_setDefaultTopicPrefix

def blpapi_SessionOptions_setAllowMultipleCorrelatorsPerMsg(parameters, allowMultipleCorrelatorsPerMsg):
    return _internals.blpapi_SessionOptions_setAllowMultipleCorrelatorsPerMsg(parameters, allowMultipleCorrelatorsPerMsg)
blpapi_SessionOptions_setAllowMultipleCorrelatorsPerMsg = _internals.blpapi_SessionOptions_setAllowMultipleCorrelatorsPerMsg

def blpapi_SessionOptions_setClientMode(parameters, clientMode):
    return _internals.blpapi_SessionOptions_setClientMode(parameters, clientMode)
blpapi_SessionOptions_setClientMode = _internals.blpapi_SessionOptions_setClientMode

def blpapi_SessionOptions_setMaxPendingRequests(parameters, maxPendingRequests):
    return _internals.blpapi_SessionOptions_setMaxPendingRequests(parameters, maxPendingRequests)
blpapi_SessionOptions_setMaxPendingRequests = _internals.blpapi_SessionOptions_setMaxPendingRequests

def blpapi_SessionOptions_setAutoRestartOnDisconnection(parameters, autoRestart):
    return _internals.blpapi_SessionOptions_setAutoRestartOnDisconnection(parameters, autoRestart)
blpapi_SessionOptions_setAutoRestartOnDisconnection = _internals.blpapi_SessionOptions_setAutoRestartOnDisconnection

def blpapi_SessionOptions_setAuthenticationOptions(parameters, authOptions):
    return _internals.blpapi_SessionOptions_setAuthenticationOptions(parameters, authOptions)
blpapi_SessionOptions_setAuthenticationOptions = _internals.blpapi_SessionOptions_setAuthenticationOptions

def blpapi_SessionOptions_setNumStartAttempts(parameters, numStartAttempts):
    return _internals.blpapi_SessionOptions_setNumStartAttempts(parameters, numStartAttempts)
blpapi_SessionOptions_setNumStartAttempts = _internals.blpapi_SessionOptions_setNumStartAttempts

def blpapi_SessionOptions_setMaxEventQueueSize(parameters, maxEventQueueSize):
    return _internals.blpapi_SessionOptions_setMaxEventQueueSize(parameters, maxEventQueueSize)
blpapi_SessionOptions_setMaxEventQueueSize = _internals.blpapi_SessionOptions_setMaxEventQueueSize

def blpapi_SessionOptions_setSlowConsumerWarningHiWaterMark(parameters, hiWaterMark):
    return _internals.blpapi_SessionOptions_setSlowConsumerWarningHiWaterMark(parameters, hiWaterMark)
blpapi_SessionOptions_setSlowConsumerWarningHiWaterMark = _internals.blpapi_SessionOptions_setSlowConsumerWarningHiWaterMark

def blpapi_SessionOptions_setSlowConsumerWarningLoWaterMark(parameters, loWaterMark):
    return _internals.blpapi_SessionOptions_setSlowConsumerWarningLoWaterMark(parameters, loWaterMark)
blpapi_SessionOptions_setSlowConsumerWarningLoWaterMark = _internals.blpapi_SessionOptions_setSlowConsumerWarningLoWaterMark

def blpapi_SessionOptions_setDefaultKeepAliveInactivityTime(parameters, inactivityMsecs):
    return _internals.blpapi_SessionOptions_setDefaultKeepAliveInactivityTime(parameters, inactivityMsecs)
blpapi_SessionOptions_setDefaultKeepAliveInactivityTime = _internals.blpapi_SessionOptions_setDefaultKeepAliveInactivityTime

def blpapi_SessionOptions_setDefaultKeepAliveResponseTimeout(parameters, timeoutMsecs):
    return _internals.blpapi_SessionOptions_setDefaultKeepAliveResponseTimeout(parameters, timeoutMsecs)
blpapi_SessionOptions_setDefaultKeepAliveResponseTimeout = _internals.blpapi_SessionOptions_setDefaultKeepAliveResponseTimeout

def blpapi_SessionOptions_setKeepAliveEnabled(parameters, isEnabled):
    return _internals.blpapi_SessionOptions_setKeepAliveEnabled(parameters, isEnabled)
blpapi_SessionOptions_setKeepAliveEnabled = _internals.blpapi_SessionOptions_setKeepAliveEnabled

def blpapi_SessionOptions_setRecordSubscriptionDataReceiveTimes(parameters, shouldRecord):
    return _internals.blpapi_SessionOptions_setRecordSubscriptionDataReceiveTimes(parameters, shouldRecord)
blpapi_SessionOptions_setRecordSubscriptionDataReceiveTimes = _internals.blpapi_SessionOptions_setRecordSubscriptionDataReceiveTimes

def blpapi_SessionOptions_serverHost(parameters):
    return _internals.blpapi_SessionOptions_serverHost(parameters)
blpapi_SessionOptions_serverHost = _internals.blpapi_SessionOptions_serverHost

def blpapi_SessionOptions_serverPort(parameters):
    return _internals.blpapi_SessionOptions_serverPort(parameters)
blpapi_SessionOptions_serverPort = _internals.blpapi_SessionOptions_serverPort

def blpapi_SessionOptions_numServerAddresses(parameters):
    return _internals.blpapi_SessionOptions_numServerAddresses(parameters)
blpapi_SessionOptions_numServerAddresses = _internals.blpapi_SessionOptions_numServerAddresses

def blpapi_SessionOptions_getServerAddress(parameters, index):
    return _internals.blpapi_SessionOptions_getServerAddress(parameters, index)
blpapi_SessionOptions_getServerAddress = _internals.blpapi_SessionOptions_getServerAddress

def blpapi_SessionOptions_connectTimeout(parameters):
    return _internals.blpapi_SessionOptions_connectTimeout(parameters)
blpapi_SessionOptions_connectTimeout = _internals.blpapi_SessionOptions_connectTimeout

def blpapi_SessionOptions_defaultServices(parameters):
    return _internals.blpapi_SessionOptions_defaultServices(parameters)
blpapi_SessionOptions_defaultServices = _internals.blpapi_SessionOptions_defaultServices

def blpapi_SessionOptions_defaultSubscriptionService(parameters):
    return _internals.blpapi_SessionOptions_defaultSubscriptionService(parameters)
blpapi_SessionOptions_defaultSubscriptionService = _internals.blpapi_SessionOptions_defaultSubscriptionService

def blpapi_SessionOptions_defaultTopicPrefix(parameters):
    return _internals.blpapi_SessionOptions_defaultTopicPrefix(parameters)
blpapi_SessionOptions_defaultTopicPrefix = _internals.blpapi_SessionOptions_defaultTopicPrefix

def blpapi_SessionOptions_allowMultipleCorrelatorsPerMsg(parameters):
    return _internals.blpapi_SessionOptions_allowMultipleCorrelatorsPerMsg(parameters)
blpapi_SessionOptions_allowMultipleCorrelatorsPerMsg = _internals.blpapi_SessionOptions_allowMultipleCorrelatorsPerMsg

def blpapi_SessionOptions_clientMode(parameters):
    return _internals.blpapi_SessionOptions_clientMode(parameters)
blpapi_SessionOptions_clientMode = _internals.blpapi_SessionOptions_clientMode

def blpapi_SessionOptions_maxPendingRequests(parameters):
    return _internals.blpapi_SessionOptions_maxPendingRequests(parameters)
blpapi_SessionOptions_maxPendingRequests = _internals.blpapi_SessionOptions_maxPendingRequests

def blpapi_SessionOptions_autoRestartOnDisconnection(parameters):
    return _internals.blpapi_SessionOptions_autoRestartOnDisconnection(parameters)
blpapi_SessionOptions_autoRestartOnDisconnection = _internals.blpapi_SessionOptions_autoRestartOnDisconnection

def blpapi_SessionOptions_authenticationOptions(parameters):
    return _internals.blpapi_SessionOptions_authenticationOptions(parameters)
blpapi_SessionOptions_authenticationOptions = _internals.blpapi_SessionOptions_authenticationOptions

def blpapi_SessionOptions_numStartAttempts(parameters):
    return _internals.blpapi_SessionOptions_numStartAttempts(parameters)
blpapi_SessionOptions_numStartAttempts = _internals.blpapi_SessionOptions_numStartAttempts

def blpapi_SessionOptions_maxEventQueueSize(parameters):
    return _internals.blpapi_SessionOptions_maxEventQueueSize(parameters)
blpapi_SessionOptions_maxEventQueueSize = _internals.blpapi_SessionOptions_maxEventQueueSize

def blpapi_SessionOptions_slowConsumerWarningHiWaterMark(parameters):
    return _internals.blpapi_SessionOptions_slowConsumerWarningHiWaterMark(parameters)
blpapi_SessionOptions_slowConsumerWarningHiWaterMark = _internals.blpapi_SessionOptions_slowConsumerWarningHiWaterMark

def blpapi_SessionOptions_slowConsumerWarningLoWaterMark(parameters):
    return _internals.blpapi_SessionOptions_slowConsumerWarningLoWaterMark(parameters)
blpapi_SessionOptions_slowConsumerWarningLoWaterMark = _internals.blpapi_SessionOptions_slowConsumerWarningLoWaterMark

def blpapi_SessionOptions_defaultKeepAliveInactivityTime(parameters):
    return _internals.blpapi_SessionOptions_defaultKeepAliveInactivityTime(parameters)
blpapi_SessionOptions_defaultKeepAliveInactivityTime = _internals.blpapi_SessionOptions_defaultKeepAliveInactivityTime

def blpapi_SessionOptions_defaultKeepAliveResponseTimeout(parameters):
    return _internals.blpapi_SessionOptions_defaultKeepAliveResponseTimeout(parameters)
blpapi_SessionOptions_defaultKeepAliveResponseTimeout = _internals.blpapi_SessionOptions_defaultKeepAliveResponseTimeout

def blpapi_SessionOptions_keepAliveEnabled(parameters):
    return _internals.blpapi_SessionOptions_keepAliveEnabled(parameters)
blpapi_SessionOptions_keepAliveEnabled = _internals.blpapi_SessionOptions_keepAliveEnabled

def blpapi_SessionOptions_recordSubscriptionDataReceiveTimes(parameters):
    return _internals.blpapi_SessionOptions_recordSubscriptionDataReceiveTimes(parameters)
blpapi_SessionOptions_recordSubscriptionDataReceiveTimes = _internals.blpapi_SessionOptions_recordSubscriptionDataReceiveTimes

def blpapi_Name_create(nameString):
    return _internals.blpapi_Name_create(nameString)
blpapi_Name_create = _internals.blpapi_Name_create

def blpapi_Name_destroy(name):
    return _internals.blpapi_Name_destroy(name)
blpapi_Name_destroy = _internals.blpapi_Name_destroy

def blpapi_Name_equalsStr(name, string):
    return _internals.blpapi_Name_equalsStr(name, string)
blpapi_Name_equalsStr = _internals.blpapi_Name_equalsStr

def blpapi_Name_string(name):
    return _internals.blpapi_Name_string(name)
blpapi_Name_string = _internals.blpapi_Name_string

def blpapi_Name_length(name):
    return _internals.blpapi_Name_length(name)
blpapi_Name_length = _internals.blpapi_Name_length

def blpapi_Name_findName(nameString):
    return _internals.blpapi_Name_findName(nameString)
blpapi_Name_findName = _internals.blpapi_Name_findName

def blpapi_SubscriptionList_create():
    return _internals.blpapi_SubscriptionList_create()
blpapi_SubscriptionList_create = _internals.blpapi_SubscriptionList_create

def blpapi_SubscriptionList_destroy(list):
    return _internals.blpapi_SubscriptionList_destroy(list)
blpapi_SubscriptionList_destroy = _internals.blpapi_SubscriptionList_destroy

def blpapi_SubscriptionList_addResolved(list, subscriptionString, correlationId):
    return _internals.blpapi_SubscriptionList_addResolved(list, subscriptionString, correlationId)
blpapi_SubscriptionList_addResolved = _internals.blpapi_SubscriptionList_addResolved

def blpapi_SubscriptionList_clear(list):
    return _internals.blpapi_SubscriptionList_clear(list)
blpapi_SubscriptionList_clear = _internals.blpapi_SubscriptionList_clear

def blpapi_SubscriptionList_append(dest, src):
    return _internals.blpapi_SubscriptionList_append(dest, src)
blpapi_SubscriptionList_append = _internals.blpapi_SubscriptionList_append

def blpapi_SubscriptionList_size(list):
    return _internals.blpapi_SubscriptionList_size(list)
blpapi_SubscriptionList_size = _internals.blpapi_SubscriptionList_size

def blpapi_SubscriptionList_correlationIdAt(list, index):
    return _internals.blpapi_SubscriptionList_correlationIdAt(list, index)
blpapi_SubscriptionList_correlationIdAt = _internals.blpapi_SubscriptionList_correlationIdAt

def blpapi_SubscriptionList_topicStringAt(list, index):
    return _internals.blpapi_SubscriptionList_topicStringAt(list, index)
blpapi_SubscriptionList_topicStringAt = _internals.blpapi_SubscriptionList_topicStringAt

def blpapi_SubscriptionList_isResolvedAt(list, index):
    return _internals.blpapi_SubscriptionList_isResolvedAt(list, index)
blpapi_SubscriptionList_isResolvedAt = _internals.blpapi_SubscriptionList_isResolvedAt
class blpapi_Datetime_tag(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, blpapi_Datetime_tag, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, blpapi_Datetime_tag, name)
    __repr__ = _swig_repr
    __swig_setmethods__["parts"] = _internals.blpapi_Datetime_tag_parts_set
    __swig_getmethods__["parts"] = _internals.blpapi_Datetime_tag_parts_get
    if _newclass:
        parts = _swig_property(_internals.blpapi_Datetime_tag_parts_get, _internals.blpapi_Datetime_tag_parts_set)
    __swig_setmethods__["hours"] = _internals.blpapi_Datetime_tag_hours_set
    __swig_getmethods__["hours"] = _internals.blpapi_Datetime_tag_hours_get
    if _newclass:
        hours = _swig_property(_internals.blpapi_Datetime_tag_hours_get, _internals.blpapi_Datetime_tag_hours_set)
    __swig_setmethods__["minutes"] = _internals.blpapi_Datetime_tag_minutes_set
    __swig_getmethods__["minutes"] = _internals.blpapi_Datetime_tag_minutes_get
    if _newclass:
        minutes = _swig_property(_internals.blpapi_Datetime_tag_minutes_get, _internals.blpapi_Datetime_tag_minutes_set)
    __swig_setmethods__["seconds"] = _internals.blpapi_Datetime_tag_seconds_set
    __swig_getmethods__["seconds"] = _internals.blpapi_Datetime_tag_seconds_get
    if _newclass:
        seconds = _swig_property(_internals.blpapi_Datetime_tag_seconds_get, _internals.blpapi_Datetime_tag_seconds_set)
    __swig_setmethods__["milliSeconds"] = _internals.blpapi_Datetime_tag_milliSeconds_set
    __swig_getmethods__["milliSeconds"] = _internals.blpapi_Datetime_tag_milliSeconds_get
    if _newclass:
        milliSeconds = _swig_property(_internals.blpapi_Datetime_tag_milliSeconds_get, _internals.blpapi_Datetime_tag_milliSeconds_set)
    __swig_setmethods__["month"] = _internals.blpapi_Datetime_tag_month_set
    __swig_getmethods__["month"] = _internals.blpapi_Datetime_tag_month_get
    if _newclass:
        month = _swig_property(_internals.blpapi_Datetime_tag_month_get, _internals.blpapi_Datetime_tag_month_set)
    __swig_setmethods__["day"] = _internals.blpapi_Datetime_tag_day_set
    __swig_getmethods__["day"] = _internals.blpapi_Datetime_tag_day_get
    if _newclass:
        day = _swig_property(_internals.blpapi_Datetime_tag_day_get, _internals.blpapi_Datetime_tag_day_set)
    __swig_setmethods__["year"] = _internals.blpapi_Datetime_tag_year_set
    __swig_getmethods__["year"] = _internals.blpapi_Datetime_tag_year_get
    if _newclass:
        year = _swig_property(_internals.blpapi_Datetime_tag_year_get, _internals.blpapi_Datetime_tag_year_set)
    __swig_setmethods__["offset"] = _internals.blpapi_Datetime_tag_offset_set
    __swig_getmethods__["offset"] = _internals.blpapi_Datetime_tag_offset_get
    if _newclass:
        offset = _swig_property(_internals.blpapi_Datetime_tag_offset_get, _internals.blpapi_Datetime_tag_offset_set)

    def __init__(self):
        this = _internals.new_blpapi_Datetime_tag()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _internals.delete_blpapi_Datetime_tag
    __del__ = lambda self: None
blpapi_Datetime_tag_swigregister = _internals.blpapi_Datetime_tag_swigregister
blpapi_Datetime_tag_swigregister(blpapi_Datetime_tag)

class blpapi_HighPrecisionDatetime_tag(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, blpapi_HighPrecisionDatetime_tag, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, blpapi_HighPrecisionDatetime_tag, name)
    __repr__ = _swig_repr
    __swig_setmethods__["datetime"] = _internals.blpapi_HighPrecisionDatetime_tag_datetime_set
    __swig_getmethods__["datetime"] = _internals.blpapi_HighPrecisionDatetime_tag_datetime_get
    if _newclass:
        datetime = _swig_property(_internals.blpapi_HighPrecisionDatetime_tag_datetime_get, _internals.blpapi_HighPrecisionDatetime_tag_datetime_set)
    __swig_setmethods__["picoseconds"] = _internals.blpapi_HighPrecisionDatetime_tag_picoseconds_set
    __swig_getmethods__["picoseconds"] = _internals.blpapi_HighPrecisionDatetime_tag_picoseconds_get
    if _newclass:
        picoseconds = _swig_property(_internals.blpapi_HighPrecisionDatetime_tag_picoseconds_get, _internals.blpapi_HighPrecisionDatetime_tag_picoseconds_set)

    def __init__(self):
        this = _internals.new_blpapi_HighPrecisionDatetime_tag()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _internals.delete_blpapi_HighPrecisionDatetime_tag
    __del__ = lambda self: None
blpapi_HighPrecisionDatetime_tag_swigregister = _internals.blpapi_HighPrecisionDatetime_tag_swigregister
blpapi_HighPrecisionDatetime_tag_swigregister(blpapi_HighPrecisionDatetime_tag)


def blpapi_HighPrecisionDatetime_compare(lhs, rhs):
    return _internals.blpapi_HighPrecisionDatetime_compare(lhs, rhs)
blpapi_HighPrecisionDatetime_compare = _internals.blpapi_HighPrecisionDatetime_compare

def blpapi_HighPrecisionDatetime_print(datetime, streamWriter, stream, level, spacesPerLevel):
    return _internals.blpapi_HighPrecisionDatetime_print(datetime, streamWriter, stream, level, spacesPerLevel)
blpapi_HighPrecisionDatetime_print = _internals.blpapi_HighPrecisionDatetime_print

def blpapi_HighPrecisionDatetime_fromTimePoint(datetime, timePoint, offset):
    return _internals.blpapi_HighPrecisionDatetime_fromTimePoint(datetime, timePoint, offset)
blpapi_HighPrecisionDatetime_fromTimePoint = _internals.blpapi_HighPrecisionDatetime_fromTimePoint

def blpapi_Constant_name(constant):
    return _internals.blpapi_Constant_name(constant)
blpapi_Constant_name = _internals.blpapi_Constant_name

def blpapi_Constant_description(constant):
    return _internals.blpapi_Constant_description(constant)
blpapi_Constant_description = _internals.blpapi_Constant_description

def blpapi_Constant_status(constant):
    return _internals.blpapi_Constant_status(constant)
blpapi_Constant_status = _internals.blpapi_Constant_status

def blpapi_Constant_datatype(constant):
    return _internals.blpapi_Constant_datatype(constant)
blpapi_Constant_datatype = _internals.blpapi_Constant_datatype

def blpapi_Constant_getValueAsInt64(constant):
    return _internals.blpapi_Constant_getValueAsInt64(constant)
blpapi_Constant_getValueAsInt64 = _internals.blpapi_Constant_getValueAsInt64

def blpapi_Constant_getValueAsFloat64(constant):
    return _internals.blpapi_Constant_getValueAsFloat64(constant)
blpapi_Constant_getValueAsFloat64 = _internals.blpapi_Constant_getValueAsFloat64

def blpapi_Constant_getValueAsDatetime(constant):
    return _internals.blpapi_Constant_getValueAsDatetime(constant)
blpapi_Constant_getValueAsDatetime = _internals.blpapi_Constant_getValueAsDatetime

def blpapi_Constant_getValueAsString(constant):
    return _internals.blpapi_Constant_getValueAsString(constant)
blpapi_Constant_getValueAsString = _internals.blpapi_Constant_getValueAsString

def blpapi_ConstantList_name(list):
    return _internals.blpapi_ConstantList_name(list)
blpapi_ConstantList_name = _internals.blpapi_ConstantList_name

def blpapi_ConstantList_description(list):
    return _internals.blpapi_ConstantList_description(list)
blpapi_ConstantList_description = _internals.blpapi_ConstantList_description

def blpapi_ConstantList_numConstants(list):
    return _internals.blpapi_ConstantList_numConstants(list)
blpapi_ConstantList_numConstants = _internals.blpapi_ConstantList_numConstants

def blpapi_ConstantList_datatype(constant):
    return _internals.blpapi_ConstantList_datatype(constant)
blpapi_ConstantList_datatype = _internals.blpapi_ConstantList_datatype

def blpapi_ConstantList_status(list):
    return _internals.blpapi_ConstantList_status(list)
blpapi_ConstantList_status = _internals.blpapi_ConstantList_status

def blpapi_ConstantList_getConstant(constant, nameString, name):
    return _internals.blpapi_ConstantList_getConstant(constant, nameString, name)
blpapi_ConstantList_getConstant = _internals.blpapi_ConstantList_getConstant

def blpapi_ConstantList_getConstantAt(constant, index):
    return _internals.blpapi_ConstantList_getConstantAt(constant, index)
blpapi_ConstantList_getConstantAt = _internals.blpapi_ConstantList_getConstantAt

def blpapi_SchemaElementDefinition_name(field):
    return _internals.blpapi_SchemaElementDefinition_name(field)
blpapi_SchemaElementDefinition_name = _internals.blpapi_SchemaElementDefinition_name

def blpapi_SchemaElementDefinition_description(field):
    return _internals.blpapi_SchemaElementDefinition_description(field)
blpapi_SchemaElementDefinition_description = _internals.blpapi_SchemaElementDefinition_description

def blpapi_SchemaElementDefinition_status(field):
    return _internals.blpapi_SchemaElementDefinition_status(field)
blpapi_SchemaElementDefinition_status = _internals.blpapi_SchemaElementDefinition_status

def blpapi_SchemaElementDefinition_type(field):
    return _internals.blpapi_SchemaElementDefinition_type(field)
blpapi_SchemaElementDefinition_type = _internals.blpapi_SchemaElementDefinition_type

def blpapi_SchemaElementDefinition_numAlternateNames(field):
    return _internals.blpapi_SchemaElementDefinition_numAlternateNames(field)
blpapi_SchemaElementDefinition_numAlternateNames = _internals.blpapi_SchemaElementDefinition_numAlternateNames

def blpapi_SchemaElementDefinition_getAlternateName(field, index):
    return _internals.blpapi_SchemaElementDefinition_getAlternateName(field, index)
blpapi_SchemaElementDefinition_getAlternateName = _internals.blpapi_SchemaElementDefinition_getAlternateName

def blpapi_SchemaElementDefinition_minValues(field):
    return _internals.blpapi_SchemaElementDefinition_minValues(field)
blpapi_SchemaElementDefinition_minValues = _internals.blpapi_SchemaElementDefinition_minValues

def blpapi_SchemaElementDefinition_maxValues(field):
    return _internals.blpapi_SchemaElementDefinition_maxValues(field)
blpapi_SchemaElementDefinition_maxValues = _internals.blpapi_SchemaElementDefinition_maxValues

def blpapi_SchemaTypeDefinition_name(type):
    return _internals.blpapi_SchemaTypeDefinition_name(type)
blpapi_SchemaTypeDefinition_name = _internals.blpapi_SchemaTypeDefinition_name

def blpapi_SchemaTypeDefinition_description(type):
    return _internals.blpapi_SchemaTypeDefinition_description(type)
blpapi_SchemaTypeDefinition_description = _internals.blpapi_SchemaTypeDefinition_description

def blpapi_SchemaTypeDefinition_status(type):
    return _internals.blpapi_SchemaTypeDefinition_status(type)
blpapi_SchemaTypeDefinition_status = _internals.blpapi_SchemaTypeDefinition_status

def blpapi_SchemaTypeDefinition_datatype(type):
    return _internals.blpapi_SchemaTypeDefinition_datatype(type)
blpapi_SchemaTypeDefinition_datatype = _internals.blpapi_SchemaTypeDefinition_datatype

def blpapi_SchemaTypeDefinition_isComplexType(type):
    return _internals.blpapi_SchemaTypeDefinition_isComplexType(type)
blpapi_SchemaTypeDefinition_isComplexType = _internals.blpapi_SchemaTypeDefinition_isComplexType

def blpapi_SchemaTypeDefinition_isSimpleType(type):
    return _internals.blpapi_SchemaTypeDefinition_isSimpleType(type)
blpapi_SchemaTypeDefinition_isSimpleType = _internals.blpapi_SchemaTypeDefinition_isSimpleType

def blpapi_SchemaTypeDefinition_isEnumerationType(type):
    return _internals.blpapi_SchemaTypeDefinition_isEnumerationType(type)
blpapi_SchemaTypeDefinition_isEnumerationType = _internals.blpapi_SchemaTypeDefinition_isEnumerationType

def blpapi_SchemaTypeDefinition_numElementDefinitions(type):
    return _internals.blpapi_SchemaTypeDefinition_numElementDefinitions(type)
blpapi_SchemaTypeDefinition_numElementDefinitions = _internals.blpapi_SchemaTypeDefinition_numElementDefinitions

def blpapi_SchemaTypeDefinition_getElementDefinition(type, nameString, name):
    return _internals.blpapi_SchemaTypeDefinition_getElementDefinition(type, nameString, name)
blpapi_SchemaTypeDefinition_getElementDefinition = _internals.blpapi_SchemaTypeDefinition_getElementDefinition

def blpapi_SchemaTypeDefinition_getElementDefinitionAt(type, index):
    return _internals.blpapi_SchemaTypeDefinition_getElementDefinitionAt(type, index)
blpapi_SchemaTypeDefinition_getElementDefinitionAt = _internals.blpapi_SchemaTypeDefinition_getElementDefinitionAt

def blpapi_SchemaTypeDefinition_enumeration(element):
    return _internals.blpapi_SchemaTypeDefinition_enumeration(element)
blpapi_SchemaTypeDefinition_enumeration = _internals.blpapi_SchemaTypeDefinition_enumeration

def blpapi_Request_destroy(request):
    return _internals.blpapi_Request_destroy(request)
blpapi_Request_destroy = _internals.blpapi_Request_destroy

def blpapi_Request_elements(request):
    return _internals.blpapi_Request_elements(request)
blpapi_Request_elements = _internals.blpapi_Request_elements

def blpapi_Request_setPreferredRoute(request, correlationId):
    return _internals.blpapi_Request_setPreferredRoute(request, correlationId)
blpapi_Request_setPreferredRoute = _internals.blpapi_Request_setPreferredRoute

def blpapi_Operation_name(service):
    return _internals.blpapi_Operation_name(service)
blpapi_Operation_name = _internals.blpapi_Operation_name

def blpapi_Operation_description(service):
    return _internals.blpapi_Operation_description(service)
blpapi_Operation_description = _internals.blpapi_Operation_description

def blpapi_Operation_requestDefinition(service):
    return _internals.blpapi_Operation_requestDefinition(service)
blpapi_Operation_requestDefinition = _internals.blpapi_Operation_requestDefinition

def blpapi_Operation_numResponseDefinitions(service):
    return _internals.blpapi_Operation_numResponseDefinitions(service)
blpapi_Operation_numResponseDefinitions = _internals.blpapi_Operation_numResponseDefinitions

def blpapi_Operation_responseDefinition(service, index):
    return _internals.blpapi_Operation_responseDefinition(service, index)
blpapi_Operation_responseDefinition = _internals.blpapi_Operation_responseDefinition

def blpapi_Service_name(service):
    return _internals.blpapi_Service_name(service)
blpapi_Service_name = _internals.blpapi_Service_name

def blpapi_Service_description(service):
    return _internals.blpapi_Service_description(service)
blpapi_Service_description = _internals.blpapi_Service_description

def blpapi_Service_numOperations(service):
    return _internals.blpapi_Service_numOperations(service)
blpapi_Service_numOperations = _internals.blpapi_Service_numOperations

def blpapi_Service_numEventDefinitions(service):
    return _internals.blpapi_Service_numEventDefinitions(service)
blpapi_Service_numEventDefinitions = _internals.blpapi_Service_numEventDefinitions

def blpapi_Service_addRef(service):
    return _internals.blpapi_Service_addRef(service)
blpapi_Service_addRef = _internals.blpapi_Service_addRef

def blpapi_Service_release(service):
    return _internals.blpapi_Service_release(service)
blpapi_Service_release = _internals.blpapi_Service_release

def blpapi_Service_authorizationServiceName(service):
    return _internals.blpapi_Service_authorizationServiceName(service)
blpapi_Service_authorizationServiceName = _internals.blpapi_Service_authorizationServiceName

def blpapi_Service_getOperation(service, nameString, name):
    return _internals.blpapi_Service_getOperation(service, nameString, name)
blpapi_Service_getOperation = _internals.blpapi_Service_getOperation

def blpapi_Service_getOperationAt(service, index):
    return _internals.blpapi_Service_getOperationAt(service, index)
blpapi_Service_getOperationAt = _internals.blpapi_Service_getOperationAt

def blpapi_Service_getEventDefinition(service, nameString, name):
    return _internals.blpapi_Service_getEventDefinition(service, nameString, name)
blpapi_Service_getEventDefinition = _internals.blpapi_Service_getEventDefinition

def blpapi_Service_getEventDefinitionAt(service, index):
    return _internals.blpapi_Service_getEventDefinitionAt(service, index)
blpapi_Service_getEventDefinitionAt = _internals.blpapi_Service_getEventDefinitionAt

def blpapi_Service_createRequest(service, operation):
    return _internals.blpapi_Service_createRequest(service, operation)
blpapi_Service_createRequest = _internals.blpapi_Service_createRequest

def blpapi_Service_createAuthorizationRequest(service, operation):
    return _internals.blpapi_Service_createAuthorizationRequest(service, operation)
blpapi_Service_createAuthorizationRequest = _internals.blpapi_Service_createAuthorizationRequest

def blpapi_Service_createPublishEvent(service):
    return _internals.blpapi_Service_createPublishEvent(service)
blpapi_Service_createPublishEvent = _internals.blpapi_Service_createPublishEvent

def blpapi_Service_createAdminEvent(service):
    return _internals.blpapi_Service_createAdminEvent(service)
blpapi_Service_createAdminEvent = _internals.blpapi_Service_createAdminEvent

def blpapi_Service_createResponseEvent(service, correlationId):
    return _internals.blpapi_Service_createResponseEvent(service, correlationId)
blpapi_Service_createResponseEvent = _internals.blpapi_Service_createResponseEvent

def blpapi_Message_messageType(message):
    return _internals.blpapi_Message_messageType(message)
blpapi_Message_messageType = _internals.blpapi_Message_messageType

def blpapi_Message_topicName(message):
    return _internals.blpapi_Message_topicName(message)
blpapi_Message_topicName = _internals.blpapi_Message_topicName

def blpapi_Message_service(message):
    return _internals.blpapi_Message_service(message)
blpapi_Message_service = _internals.blpapi_Message_service

def blpapi_Message_numCorrelationIds(message):
    return _internals.blpapi_Message_numCorrelationIds(message)
blpapi_Message_numCorrelationIds = _internals.blpapi_Message_numCorrelationIds

def blpapi_Message_correlationId(message, index):
    return _internals.blpapi_Message_correlationId(message, index)
blpapi_Message_correlationId = _internals.blpapi_Message_correlationId

def blpapi_Message_elements(message):
    return _internals.blpapi_Message_elements(message)
blpapi_Message_elements = _internals.blpapi_Message_elements

def blpapi_Message_fragmentType(message):
    return _internals.blpapi_Message_fragmentType(message)
blpapi_Message_fragmentType = _internals.blpapi_Message_fragmentType

def blpapi_Message_addRef(message):
    return _internals.blpapi_Message_addRef(message)
blpapi_Message_addRef = _internals.blpapi_Message_addRef

def blpapi_Message_release(message):
    return _internals.blpapi_Message_release(message)
blpapi_Message_release = _internals.blpapi_Message_release

def blpapi_Message_timeReceived(message, timeReceived):
    return _internals.blpapi_Message_timeReceived(message, timeReceived)
blpapi_Message_timeReceived = _internals.blpapi_Message_timeReceived

def blpapi_Event_eventType(event):
    return _internals.blpapi_Event_eventType(event)
blpapi_Event_eventType = _internals.blpapi_Event_eventType

def blpapi_Event_release(event):
    return _internals.blpapi_Event_release(event)
blpapi_Event_release = _internals.blpapi_Event_release

def blpapi_EventQueue_create():
    return _internals.blpapi_EventQueue_create()
blpapi_EventQueue_create = _internals.blpapi_EventQueue_create

def blpapi_EventQueue_destroy(eventQueue):
    return _internals.blpapi_EventQueue_destroy(eventQueue)
blpapi_EventQueue_destroy = _internals.blpapi_EventQueue_destroy

def blpapi_EventQueue_nextEvent(eventQueue, timeout):
    return _internals.blpapi_EventQueue_nextEvent(eventQueue, timeout)
blpapi_EventQueue_nextEvent = _internals.blpapi_EventQueue_nextEvent

def blpapi_EventQueue_purge(eventQueue):
    return _internals.blpapi_EventQueue_purge(eventQueue)
blpapi_EventQueue_purge = _internals.blpapi_EventQueue_purge

def blpapi_EventQueue_tryNextEvent(eventQueue):
    return _internals.blpapi_EventQueue_tryNextEvent(eventQueue)
blpapi_EventQueue_tryNextEvent = _internals.blpapi_EventQueue_tryNextEvent

def blpapi_MessageIterator_create(event):
    return _internals.blpapi_MessageIterator_create(event)
blpapi_MessageIterator_create = _internals.blpapi_MessageIterator_create

def blpapi_MessageIterator_destroy(iterator):
    return _internals.blpapi_MessageIterator_destroy(iterator)
blpapi_MessageIterator_destroy = _internals.blpapi_MessageIterator_destroy

def blpapi_MessageIterator_next(iterator):
    return _internals.blpapi_MessageIterator_next(iterator)
blpapi_MessageIterator_next = _internals.blpapi_MessageIterator_next

def blpapi_Identity_release(handle):
    return _internals.blpapi_Identity_release(handle)
blpapi_Identity_release = _internals.blpapi_Identity_release

def blpapi_Identity_addRef(handle):
    return _internals.blpapi_Identity_addRef(handle)
blpapi_Identity_addRef = _internals.blpapi_Identity_addRef

def blpapi_Identity_hasEntitlements(handle, service, eidElement, entitlementIds, numEntitlements, failedEntitlements, failedEntitlementsCount):
    return _internals.blpapi_Identity_hasEntitlements(handle, service, eidElement, entitlementIds, numEntitlements, failedEntitlements, failedEntitlementsCount)
blpapi_Identity_hasEntitlements = _internals.blpapi_Identity_hasEntitlements

def blpapi_Identity_isAuthorized(handle, service):
    return _internals.blpapi_Identity_isAuthorized(handle, service)
blpapi_Identity_isAuthorized = _internals.blpapi_Identity_isAuthorized

def blpapi_Identity_getSeatType(handle):
    return _internals.blpapi_Identity_getSeatType(handle)
blpapi_Identity_getSeatType = _internals.blpapi_Identity_getSeatType

def blpapi_AbstractSession_cancel(session, correlationIds, numCorrelationIds, requestLabel, requestLabelLen):
    return _internals.blpapi_AbstractSession_cancel(session, correlationIds, numCorrelationIds, requestLabel, requestLabelLen)
blpapi_AbstractSession_cancel = _internals.blpapi_AbstractSession_cancel

def blpapi_AbstractSession_sendAuthorizationRequest(session, request, identity, correlationId, eventQueue, requestLabel, requestLabelLen):
    return _internals.blpapi_AbstractSession_sendAuthorizationRequest(session, request, identity, correlationId, eventQueue, requestLabel, requestLabelLen)
blpapi_AbstractSession_sendAuthorizationRequest = _internals.blpapi_AbstractSession_sendAuthorizationRequest

def blpapi_AbstractSession_openService(session, serviceIdentifier):
    return _internals.blpapi_AbstractSession_openService(session, serviceIdentifier)
blpapi_AbstractSession_openService = _internals.blpapi_AbstractSession_openService

def blpapi_AbstractSession_openServiceAsync(session, serviceIdentifier, correlationId):
    return _internals.blpapi_AbstractSession_openServiceAsync(session, serviceIdentifier, correlationId)
blpapi_AbstractSession_openServiceAsync = _internals.blpapi_AbstractSession_openServiceAsync

def blpapi_AbstractSession_generateToken(session, correlationId, eventQueue):
    return _internals.blpapi_AbstractSession_generateToken(session, correlationId, eventQueue)
blpapi_AbstractSession_generateToken = _internals.blpapi_AbstractSession_generateToken

def blpapi_AbstractSession_getService(session, serviceIdentifier):
    return _internals.blpapi_AbstractSession_getService(session, serviceIdentifier)
blpapi_AbstractSession_getService = _internals.blpapi_AbstractSession_getService

def blpapi_AbstractSession_createIdentity(session):
    return _internals.blpapi_AbstractSession_createIdentity(session)
blpapi_AbstractSession_createIdentity = _internals.blpapi_AbstractSession_createIdentity

def blpapi_Session_start(session):
    return _internals.blpapi_Session_start(session)
blpapi_Session_start = _internals.blpapi_Session_start

def blpapi_Session_startAsync(session):
    return _internals.blpapi_Session_startAsync(session)
blpapi_Session_startAsync = _internals.blpapi_Session_startAsync

def blpapi_Session_stop(session):
    return _internals.blpapi_Session_stop(session)
blpapi_Session_stop = _internals.blpapi_Session_stop

def blpapi_Session_stopAsync(session):
    return _internals.blpapi_Session_stopAsync(session)
blpapi_Session_stopAsync = _internals.blpapi_Session_stopAsync

def blpapi_Session_nextEvent(session, timeoutInMilliseconds):
    return _internals.blpapi_Session_nextEvent(session, timeoutInMilliseconds)
blpapi_Session_nextEvent = _internals.blpapi_Session_nextEvent

def blpapi_Session_tryNextEvent(session):
    return _internals.blpapi_Session_tryNextEvent(session)
blpapi_Session_tryNextEvent = _internals.blpapi_Session_tryNextEvent

def blpapi_Session_subscribe(session, subscriptionList, handle, requestLabel, requestLabelLen):
    return _internals.blpapi_Session_subscribe(session, subscriptionList, handle, requestLabel, requestLabelLen)
blpapi_Session_subscribe = _internals.blpapi_Session_subscribe

def blpapi_Session_resubscribe(session, resubscriptionList, requestLabel, requestLabelLen):
    return _internals.blpapi_Session_resubscribe(session, resubscriptionList, requestLabel, requestLabelLen)
blpapi_Session_resubscribe = _internals.blpapi_Session_resubscribe

def blpapi_Session_resubscribeWithId(session, resubscriptionList, resubscriptionId, requestLabel, requestLabelLen):
    return _internals.blpapi_Session_resubscribeWithId(session, resubscriptionList, resubscriptionId, requestLabel, requestLabelLen)
blpapi_Session_resubscribeWithId = _internals.blpapi_Session_resubscribeWithId

def blpapi_Session_unsubscribe(session, unsubscriptionList, requestLabel, requestLabelLen):
    return _internals.blpapi_Session_unsubscribe(session, unsubscriptionList, requestLabel, requestLabelLen)
blpapi_Session_unsubscribe = _internals.blpapi_Session_unsubscribe

def blpapi_Session_setStatusCorrelationId(session, service, identity, correlationId):
    return _internals.blpapi_Session_setStatusCorrelationId(session, service, identity, correlationId)
blpapi_Session_setStatusCorrelationId = _internals.blpapi_Session_setStatusCorrelationId

def blpapi_Session_sendRequest(session, request, correlationId, identity, eventQueue, requestLabel, requestLabelLen):
    return _internals.blpapi_Session_sendRequest(session, request, correlationId, identity, eventQueue, requestLabel, requestLabelLen)
blpapi_Session_sendRequest = _internals.blpapi_Session_sendRequest

def blpapi_Session_getAbstractSession(session):
    return _internals.blpapi_Session_getAbstractSession(session)
blpapi_Session_getAbstractSession = _internals.blpapi_Session_getAbstractSession

def blpapi_ResolutionList_extractAttributeFromResolutionSuccess(message, attribute):
    return _internals.blpapi_ResolutionList_extractAttributeFromResolutionSuccess(message, attribute)
blpapi_ResolutionList_extractAttributeFromResolutionSuccess = _internals.blpapi_ResolutionList_extractAttributeFromResolutionSuccess

def blpapi_ResolutionList_create(arg1):
    return _internals.blpapi_ResolutionList_create(arg1)
blpapi_ResolutionList_create = _internals.blpapi_ResolutionList_create

def blpapi_ResolutionList_destroy(list):
    return _internals.blpapi_ResolutionList_destroy(list)
blpapi_ResolutionList_destroy = _internals.blpapi_ResolutionList_destroy

def blpapi_ResolutionList_add(list, topic, correlationId):
    return _internals.blpapi_ResolutionList_add(list, topic, correlationId)
blpapi_ResolutionList_add = _internals.blpapi_ResolutionList_add

def blpapi_ResolutionList_addFromMessage(list, topic, correlationId):
    return _internals.blpapi_ResolutionList_addFromMessage(list, topic, correlationId)
blpapi_ResolutionList_addFromMessage = _internals.blpapi_ResolutionList_addFromMessage

def blpapi_ResolutionList_addAttribute(list, name):
    return _internals.blpapi_ResolutionList_addAttribute(list, name)
blpapi_ResolutionList_addAttribute = _internals.blpapi_ResolutionList_addAttribute

def blpapi_ResolutionList_correlationIdAt(list, index):
    return _internals.blpapi_ResolutionList_correlationIdAt(list, index)
blpapi_ResolutionList_correlationIdAt = _internals.blpapi_ResolutionList_correlationIdAt

def blpapi_ResolutionList_topicString(list, id):
    return _internals.blpapi_ResolutionList_topicString(list, id)
blpapi_ResolutionList_topicString = _internals.blpapi_ResolutionList_topicString

def blpapi_ResolutionList_topicStringAt(list, index):
    return _internals.blpapi_ResolutionList_topicStringAt(list, index)
blpapi_ResolutionList_topicStringAt = _internals.blpapi_ResolutionList_topicStringAt

def blpapi_ResolutionList_status(list, id):
    return _internals.blpapi_ResolutionList_status(list, id)
blpapi_ResolutionList_status = _internals.blpapi_ResolutionList_status

def blpapi_ResolutionList_statusAt(list, index):
    return _internals.blpapi_ResolutionList_statusAt(list, index)
blpapi_ResolutionList_statusAt = _internals.blpapi_ResolutionList_statusAt

def blpapi_ResolutionList_attribute(list, attribute, id):
    return _internals.blpapi_ResolutionList_attribute(list, attribute, id)
blpapi_ResolutionList_attribute = _internals.blpapi_ResolutionList_attribute

def blpapi_ResolutionList_attributeAt(list, attribute, index):
    return _internals.blpapi_ResolutionList_attributeAt(list, attribute, index)
blpapi_ResolutionList_attributeAt = _internals.blpapi_ResolutionList_attributeAt

def blpapi_ResolutionList_message(list, id):
    return _internals.blpapi_ResolutionList_message(list, id)
blpapi_ResolutionList_message = _internals.blpapi_ResolutionList_message

def blpapi_ResolutionList_messageAt(list, index):
    return _internals.blpapi_ResolutionList_messageAt(list, index)
blpapi_ResolutionList_messageAt = _internals.blpapi_ResolutionList_messageAt

def blpapi_ResolutionList_size(list):
    return _internals.blpapi_ResolutionList_size(list)
blpapi_ResolutionList_size = _internals.blpapi_ResolutionList_size

def blpapi_Topic_create(arg1):
    return _internals.blpapi_Topic_create(arg1)
blpapi_Topic_create = _internals.blpapi_Topic_create

def blpapi_Topic_destroy(victim):
    return _internals.blpapi_Topic_destroy(victim)
blpapi_Topic_destroy = _internals.blpapi_Topic_destroy

def blpapi_Topic_compare(lhs, rhs):
    return _internals.blpapi_Topic_compare(lhs, rhs)
blpapi_Topic_compare = _internals.blpapi_Topic_compare

def blpapi_Topic_service(topic):
    return _internals.blpapi_Topic_service(topic)
blpapi_Topic_service = _internals.blpapi_Topic_service

def blpapi_Topic_isActive(topic):
    return _internals.blpapi_Topic_isActive(topic)
blpapi_Topic_isActive = _internals.blpapi_Topic_isActive

def blpapi_TopicList_create(arg1):
    return _internals.blpapi_TopicList_create(arg1)
blpapi_TopicList_create = _internals.blpapi_TopicList_create

def blpapi_TopicList_destroy(list):
    return _internals.blpapi_TopicList_destroy(list)
blpapi_TopicList_destroy = _internals.blpapi_TopicList_destroy

def blpapi_TopicList_add(list, topic, correlationId):
    return _internals.blpapi_TopicList_add(list, topic, correlationId)
blpapi_TopicList_add = _internals.blpapi_TopicList_add

def blpapi_TopicList_addFromMessage(list, topic, correlationId):
    return _internals.blpapi_TopicList_addFromMessage(list, topic, correlationId)
blpapi_TopicList_addFromMessage = _internals.blpapi_TopicList_addFromMessage

def blpapi_TopicList_correlationIdAt(list, index):
    return _internals.blpapi_TopicList_correlationIdAt(list, index)
blpapi_TopicList_correlationIdAt = _internals.blpapi_TopicList_correlationIdAt

def blpapi_TopicList_topicString(list, id):
    return _internals.blpapi_TopicList_topicString(list, id)
blpapi_TopicList_topicString = _internals.blpapi_TopicList_topicString

def blpapi_TopicList_topicStringAt(list, index):
    return _internals.blpapi_TopicList_topicStringAt(list, index)
blpapi_TopicList_topicStringAt = _internals.blpapi_TopicList_topicStringAt

def blpapi_TopicList_status(list, id):
    return _internals.blpapi_TopicList_status(list, id)
blpapi_TopicList_status = _internals.blpapi_TopicList_status

def blpapi_TopicList_statusAt(list, index):
    return _internals.blpapi_TopicList_statusAt(list, index)
blpapi_TopicList_statusAt = _internals.blpapi_TopicList_statusAt

def blpapi_TopicList_message(list, id):
    return _internals.blpapi_TopicList_message(list, id)
blpapi_TopicList_message = _internals.blpapi_TopicList_message

def blpapi_TopicList_messageAt(list, index):
    return _internals.blpapi_TopicList_messageAt(list, index)
blpapi_TopicList_messageAt = _internals.blpapi_TopicList_messageAt

def blpapi_TopicList_size(list):
    return _internals.blpapi_TopicList_size(list)
blpapi_TopicList_size = _internals.blpapi_TopicList_size

def blpapi_ProviderSession_create(parameters, handler, dispatcher, userData):
    return _internals.blpapi_ProviderSession_create(parameters, handler, dispatcher, userData)
blpapi_ProviderSession_create = _internals.blpapi_ProviderSession_create

def blpapi_ProviderSession_destroy(session):
    return _internals.blpapi_ProviderSession_destroy(session)
blpapi_ProviderSession_destroy = _internals.blpapi_ProviderSession_destroy

def blpapi_ProviderSession_start(session):
    return _internals.blpapi_ProviderSession_start(session)
blpapi_ProviderSession_start = _internals.blpapi_ProviderSession_start

def blpapi_ProviderSession_startAsync(session):
    return _internals.blpapi_ProviderSession_startAsync(session)
blpapi_ProviderSession_startAsync = _internals.blpapi_ProviderSession_startAsync

def blpapi_ProviderSession_stop(session):
    return _internals.blpapi_ProviderSession_stop(session)
blpapi_ProviderSession_stop = _internals.blpapi_ProviderSession_stop

def blpapi_ProviderSession_stopAsync(session):
    return _internals.blpapi_ProviderSession_stopAsync(session)
blpapi_ProviderSession_stopAsync = _internals.blpapi_ProviderSession_stopAsync

def blpapi_ProviderSession_nextEvent(session, timeoutInMilliseconds):
    return _internals.blpapi_ProviderSession_nextEvent(session, timeoutInMilliseconds)
blpapi_ProviderSession_nextEvent = _internals.blpapi_ProviderSession_nextEvent

def blpapi_ProviderSession_tryNextEvent(session):
    return _internals.blpapi_ProviderSession_tryNextEvent(session)
blpapi_ProviderSession_tryNextEvent = _internals.blpapi_ProviderSession_tryNextEvent

def blpapi_ProviderSession_registerService(session, serviceName, identity, registrationOptions):
    return _internals.blpapi_ProviderSession_registerService(session, serviceName, identity, registrationOptions)
blpapi_ProviderSession_registerService = _internals.blpapi_ProviderSession_registerService

def blpapi_ProviderSession_activateSubServiceCodeRange(session, serviceName, begin, end, priority):
    return _internals.blpapi_ProviderSession_activateSubServiceCodeRange(session, serviceName, begin, end, priority)
blpapi_ProviderSession_activateSubServiceCodeRange = _internals.blpapi_ProviderSession_activateSubServiceCodeRange

def blpapi_ProviderSession_deactivateSubServiceCodeRange(session, serviceName, begin, end):
    return _internals.blpapi_ProviderSession_deactivateSubServiceCodeRange(session, serviceName, begin, end)
blpapi_ProviderSession_deactivateSubServiceCodeRange = _internals.blpapi_ProviderSession_deactivateSubServiceCodeRange

def blpapi_ProviderSession_registerServiceAsync(session, serviceName, identity, correlationId, registrationOptions):
    return _internals.blpapi_ProviderSession_registerServiceAsync(session, serviceName, identity, correlationId, registrationOptions)
blpapi_ProviderSession_registerServiceAsync = _internals.blpapi_ProviderSession_registerServiceAsync

def blpapi_ProviderSession_deregisterService(session, serviceName):
    return _internals.blpapi_ProviderSession_deregisterService(session, serviceName)
blpapi_ProviderSession_deregisterService = _internals.blpapi_ProviderSession_deregisterService

def blpapi_ProviderSession_resolve(session, resolutionList, resolveMode, identity):
    return _internals.blpapi_ProviderSession_resolve(session, resolutionList, resolveMode, identity)
blpapi_ProviderSession_resolve = _internals.blpapi_ProviderSession_resolve

def blpapi_ProviderSession_resolveAsync(session, resolutionList, resolveMode, identity):
    return _internals.blpapi_ProviderSession_resolveAsync(session, resolutionList, resolveMode, identity)
blpapi_ProviderSession_resolveAsync = _internals.blpapi_ProviderSession_resolveAsync

def blpapi_ProviderSession_createTopics(session, topicList, resolveMode, identity):
    return _internals.blpapi_ProviderSession_createTopics(session, topicList, resolveMode, identity)
blpapi_ProviderSession_createTopics = _internals.blpapi_ProviderSession_createTopics

def blpapi_ProviderSession_createTopicsAsync(session, topicList, resolveMode, identity):
    return _internals.blpapi_ProviderSession_createTopicsAsync(session, topicList, resolveMode, identity)
blpapi_ProviderSession_createTopicsAsync = _internals.blpapi_ProviderSession_createTopicsAsync

def blpapi_ProviderSession_getTopic(session, message):
    return _internals.blpapi_ProviderSession_getTopic(session, message)
blpapi_ProviderSession_getTopic = _internals.blpapi_ProviderSession_getTopic

def blpapi_ProviderSession_createTopic(session, message):
    return _internals.blpapi_ProviderSession_createTopic(session, message)
blpapi_ProviderSession_createTopic = _internals.blpapi_ProviderSession_createTopic

def blpapi_ProviderSession_createServiceStatusTopic(session, service):
    return _internals.blpapi_ProviderSession_createServiceStatusTopic(session, service)
blpapi_ProviderSession_createServiceStatusTopic = _internals.blpapi_ProviderSession_createServiceStatusTopic

def blpapi_ProviderSession_deleteTopics(session, topics, numTopics):
    return _internals.blpapi_ProviderSession_deleteTopics(session, topics, numTopics)
blpapi_ProviderSession_deleteTopics = _internals.blpapi_ProviderSession_deleteTopics

def blpapi_ProviderSession_publish(session, event):
    return _internals.blpapi_ProviderSession_publish(session, event)
blpapi_ProviderSession_publish = _internals.blpapi_ProviderSession_publish

def blpapi_ProviderSession_sendResponse(session, event, isPartialResponse):
    return _internals.blpapi_ProviderSession_sendResponse(session, event, isPartialResponse)
blpapi_ProviderSession_sendResponse = _internals.blpapi_ProviderSession_sendResponse

def blpapi_ProviderSession_getAbstractSession(session):
    return _internals.blpapi_ProviderSession_getAbstractSession(session)
blpapi_ProviderSession_getAbstractSession = _internals.blpapi_ProviderSession_getAbstractSession

def blpapi_ServiceRegistrationOptions_create():
    return _internals.blpapi_ServiceRegistrationOptions_create()
blpapi_ServiceRegistrationOptions_create = _internals.blpapi_ServiceRegistrationOptions_create

def blpapi_ServiceRegistrationOptions_duplicate(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_duplicate(parameters)
blpapi_ServiceRegistrationOptions_duplicate = _internals.blpapi_ServiceRegistrationOptions_duplicate

def blpapi_ServiceRegistrationOptions_destroy(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_destroy(parameters)
blpapi_ServiceRegistrationOptions_destroy = _internals.blpapi_ServiceRegistrationOptions_destroy

def blpapi_ServiceRegistrationOptions_copy(lhs, rhs):
    return _internals.blpapi_ServiceRegistrationOptions_copy(lhs, rhs)
blpapi_ServiceRegistrationOptions_copy = _internals.blpapi_ServiceRegistrationOptions_copy

def blpapi_ServiceRegistrationOptions_addActiveSubServiceCodeRange(parameters, start, end, priority):
    return _internals.blpapi_ServiceRegistrationOptions_addActiveSubServiceCodeRange(parameters, start, end, priority)
blpapi_ServiceRegistrationOptions_addActiveSubServiceCodeRange = _internals.blpapi_ServiceRegistrationOptions_addActiveSubServiceCodeRange

def blpapi_ServiceRegistrationOptions_removeAllActiveSubServiceCodeRanges(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_removeAllActiveSubServiceCodeRanges(parameters)
blpapi_ServiceRegistrationOptions_removeAllActiveSubServiceCodeRanges = _internals.blpapi_ServiceRegistrationOptions_removeAllActiveSubServiceCodeRanges

def blpapi_ServiceRegistrationOptions_setGroupId(parameters, groupId):
    return _internals.blpapi_ServiceRegistrationOptions_setGroupId(parameters, groupId)
blpapi_ServiceRegistrationOptions_setGroupId = _internals.blpapi_ServiceRegistrationOptions_setGroupId

def blpapi_ServiceRegistrationOptions_setServicePriority(parameters, priority):
    return _internals.blpapi_ServiceRegistrationOptions_setServicePriority(parameters, priority)
blpapi_ServiceRegistrationOptions_setServicePriority = _internals.blpapi_ServiceRegistrationOptions_setServicePriority

def blpapi_ServiceRegistrationOptions_setPartsToRegister(parameters, parts):
    return _internals.blpapi_ServiceRegistrationOptions_setPartsToRegister(parameters, parts)
blpapi_ServiceRegistrationOptions_setPartsToRegister = _internals.blpapi_ServiceRegistrationOptions_setPartsToRegister

def blpapi_ServiceRegistrationOptions_getGroupId(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_getGroupId(parameters)
blpapi_ServiceRegistrationOptions_getGroupId = _internals.blpapi_ServiceRegistrationOptions_getGroupId

def blpapi_ServiceRegistrationOptions_getServicePriority(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_getServicePriority(parameters)
blpapi_ServiceRegistrationOptions_getServicePriority = _internals.blpapi_ServiceRegistrationOptions_getServicePriority

def blpapi_ServiceRegistrationOptions_getPartsToRegister(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_getPartsToRegister(parameters)
blpapi_ServiceRegistrationOptions_getPartsToRegister = _internals.blpapi_ServiceRegistrationOptions_getPartsToRegister
# This file is compatible with both classic and new-style classes.


