# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""
This module defines internals of BLPAPI-Py and the following classes:
- CorrelationId: a key to track requests and subscriptions

Copyright 2012. Bloomberg Finance L.P.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to
deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:  The above
copyright notice and this permission notice shall be included in all copies
or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
"""

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _internals
else:
    import _internals

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


ELEMENTDEFINITION_UNBOUNDED = _internals.ELEMENTDEFINITION_UNBOUNDED
ELEMENT_INDEX_END = _internals.ELEMENT_INDEX_END
SERVICEREGISTRATIONOPTIONS_PRIORITY_MEDIUM = _internals.SERVICEREGISTRATIONOPTIONS_PRIORITY_MEDIUM
SERVICEREGISTRATIONOPTIONS_PRIORITY_HIGH = _internals.SERVICEREGISTRATIONOPTIONS_PRIORITY_HIGH
CORRELATION_TYPE_UNSET = _internals.CORRELATION_TYPE_UNSET
CORRELATION_TYPE_INT = _internals.CORRELATION_TYPE_INT
CORRELATION_TYPE_POINTER = _internals.CORRELATION_TYPE_POINTER
CORRELATION_TYPE_AUTOGEN = _internals.CORRELATION_TYPE_AUTOGEN
CORRELATION_MAX_CLASS_ID = _internals.CORRELATION_MAX_CLASS_ID
MANAGEDPTR_COPY = _internals.MANAGEDPTR_COPY
MANAGEDPTR_DESTROY = _internals.MANAGEDPTR_DESTROY
DATETIME_YEAR_PART = _internals.DATETIME_YEAR_PART
DATETIME_MONTH_PART = _internals.DATETIME_MONTH_PART
DATETIME_DAY_PART = _internals.DATETIME_DAY_PART
DATETIME_OFFSET_PART = _internals.DATETIME_OFFSET_PART
DATETIME_HOURS_PART = _internals.DATETIME_HOURS_PART
DATETIME_MINUTES_PART = _internals.DATETIME_MINUTES_PART
DATETIME_SECONDS_PART = _internals.DATETIME_SECONDS_PART
DATETIME_MILLISECONDS_PART = _internals.DATETIME_MILLISECONDS_PART
DATETIME_FRACSECONDS_PART = _internals.DATETIME_FRACSECONDS_PART
DATETIME_DATE_PART = _internals.DATETIME_DATE_PART
DATETIME_TIME_PART = _internals.DATETIME_TIME_PART
DATETIME_TIMEMILLI_PART = _internals.DATETIME_TIMEMILLI_PART
DATETIME_TIMEFRACSECONDS_PART = _internals.DATETIME_TIMEFRACSECONDS_PART
EVENTTYPE_ADMIN = _internals.EVENTTYPE_ADMIN
EVENTTYPE_SESSION_STATUS = _internals.EVENTTYPE_SESSION_STATUS
EVENTTYPE_SUBSCRIPTION_STATUS = _internals.EVENTTYPE_SUBSCRIPTION_STATUS
EVENTTYPE_REQUEST_STATUS = _internals.EVENTTYPE_REQUEST_STATUS
EVENTTYPE_RESPONSE = _internals.EVENTTYPE_RESPONSE
EVENTTYPE_PARTIAL_RESPONSE = _internals.EVENTTYPE_PARTIAL_RESPONSE
EVENTTYPE_SUBSCRIPTION_DATA = _internals.EVENTTYPE_SUBSCRIPTION_DATA
EVENTTYPE_SERVICE_STATUS = _internals.EVENTTYPE_SERVICE_STATUS
EVENTTYPE_TIMEOUT = _internals.EVENTTYPE_TIMEOUT
EVENTTYPE_AUTHORIZATION_STATUS = _internals.EVENTTYPE_AUTHORIZATION_STATUS
EVENTTYPE_RESOLUTION_STATUS = _internals.EVENTTYPE_RESOLUTION_STATUS
EVENTTYPE_TOPIC_STATUS = _internals.EVENTTYPE_TOPIC_STATUS
EVENTTYPE_TOKEN_STATUS = _internals.EVENTTYPE_TOKEN_STATUS
EVENTTYPE_REQUEST = _internals.EVENTTYPE_REQUEST
STATUS_ACTIVE = _internals.STATUS_ACTIVE
STATUS_DEPRECATED = _internals.STATUS_DEPRECATED
STATUS_INACTIVE = _internals.STATUS_INACTIVE
STATUS_PENDING_DEPRECATION = _internals.STATUS_PENDING_DEPRECATION
SUBSCRIPTIONSTATUS_UNSUBSCRIBED = _internals.SUBSCRIPTIONSTATUS_UNSUBSCRIBED
SUBSCRIPTIONSTATUS_SUBSCRIBING = _internals.SUBSCRIPTIONSTATUS_SUBSCRIBING
SUBSCRIPTIONSTATUS_SUBSCRIBED = _internals.SUBSCRIPTIONSTATUS_SUBSCRIBED
SUBSCRIPTIONSTATUS_CANCELLED = _internals.SUBSCRIPTIONSTATUS_CANCELLED
SUBSCRIPTIONSTATUS_PENDING_CANCELLATION = _internals.SUBSCRIPTIONSTATUS_PENDING_CANCELLATION
CLIENTMODE_AUTO = _internals.CLIENTMODE_AUTO
CLIENTMODE_DAPI = _internals.CLIENTMODE_DAPI
CLIENTMODE_SAPI = _internals.CLIENTMODE_SAPI
CLIENTMODE_COMPAT_33X = _internals.CLIENTMODE_COMPAT_33X
RESOLVEMODE_DONT_REGISTER_SERVICES = _internals.RESOLVEMODE_DONT_REGISTER_SERVICES
RESOLVEMODE_AUTO_REGISTER_SERVICES = _internals.RESOLVEMODE_AUTO_REGISTER_SERVICES
SEATTYPE_INVALID_SEAT = _internals.SEATTYPE_INVALID_SEAT
SEATTYPE_BPS = _internals.SEATTYPE_BPS
SEATTYPE_NONBPS = _internals.SEATTYPE_NONBPS
SERVICEREGISTRATIONOPTIONS_PRIORITY_LOW = _internals.SERVICEREGISTRATIONOPTIONS_PRIORITY_LOW
REGISTRATIONPARTS_DEFAULT = _internals.REGISTRATIONPARTS_DEFAULT
REGISTRATIONPARTS_PUBLISHING = _internals.REGISTRATIONPARTS_PUBLISHING
REGISTRATIONPARTS_OPERATIONS = _internals.REGISTRATIONPARTS_OPERATIONS
REGISTRATIONPARTS_SUBSCRIBER_RESOLUTION = _internals.REGISTRATIONPARTS_SUBSCRIBER_RESOLUTION
REGISTRATIONPARTS_PUBLISHER_RESOLUTION = _internals.REGISTRATIONPARTS_PUBLISHER_RESOLUTION
TOPICLIST_NOT_CREATED = _internals.TOPICLIST_NOT_CREATED
TOPICLIST_CREATED = _internals.TOPICLIST_CREATED
TOPICLIST_FAILURE = _internals.TOPICLIST_FAILURE
RESOLUTIONLIST_UNRESOLVED = _internals.RESOLUTIONLIST_UNRESOLVED
RESOLUTIONLIST_RESOLVED = _internals.RESOLUTIONLIST_RESOLVED
RESOLUTIONLIST_RESOLUTION_FAILURE_BAD_SERVICE = _internals.RESOLUTIONLIST_RESOLUTION_FAILURE_BAD_SERVICE
RESOLUTIONLIST_RESOLUTION_FAILURE_SERVICE_AUTHORIZATION_FAILED = _internals.RESOLUTIONLIST_RESOLUTION_FAILURE_SERVICE_AUTHORIZATION_FAILED
RESOLUTIONLIST_RESOLUTION_FAILURE_BAD_TOPIC = _internals.RESOLUTIONLIST_RESOLUTION_FAILURE_BAD_TOPIC
RESOLUTIONLIST_RESOLUTION_FAILURE_TOPIC_AUTHORIZATION_FAILED = _internals.RESOLUTIONLIST_RESOLUTION_FAILURE_TOPIC_AUTHORIZATION_FAILED
MESSAGE_FRAGMENT_NONE = _internals.MESSAGE_FRAGMENT_NONE
MESSAGE_FRAGMENT_START = _internals.MESSAGE_FRAGMENT_START
MESSAGE_FRAGMENT_INTERMEDIATE = _internals.MESSAGE_FRAGMENT_INTERMEDIATE
MESSAGE_FRAGMENT_END = _internals.MESSAGE_FRAGMENT_END
MESSAGE_RECAPTYPE_NONE = _internals.MESSAGE_RECAPTYPE_NONE
MESSAGE_RECAPTYPE_SOLICITED = _internals.MESSAGE_RECAPTYPE_SOLICITED
MESSAGE_RECAPTYPE_UNSOLICITED = _internals.MESSAGE_RECAPTYPE_UNSOLICITED
ZFPUTIL_REMOTE_8194 = _internals.ZFPUTIL_REMOTE_8194
ZFPUTIL_REMOTE_8196 = _internals.ZFPUTIL_REMOTE_8196
IDENTITYUTIL_USERTYPE_UNKNOWN = _internals.IDENTITYUTIL_USERTYPE_UNKNOWN
IDENTITYUTIL_USERTYPE_APP_PORTAL = _internals.IDENTITYUTIL_USERTYPE_APP_PORTAL
IDENTITYUTIL_USERTYPE_SANDBOX_EXCEL = _internals.IDENTITYUTIL_USERTYPE_SANDBOX_EXCEL
DATATYPE_BOOL = _internals.DATATYPE_BOOL
DATATYPE_CHAR = _internals.DATATYPE_CHAR
DATATYPE_BYTE = _internals.DATATYPE_BYTE
DATATYPE_INT32 = _internals.DATATYPE_INT32
DATATYPE_INT64 = _internals.DATATYPE_INT64
DATATYPE_FLOAT32 = _internals.DATATYPE_FLOAT32
DATATYPE_FLOAT64 = _internals.DATATYPE_FLOAT64
DATATYPE_STRING = _internals.DATATYPE_STRING
DATATYPE_BYTEARRAY = _internals.DATATYPE_BYTEARRAY
DATATYPE_DATE = _internals.DATATYPE_DATE
DATATYPE_TIME = _internals.DATATYPE_TIME
DATATYPE_DECIMAL = _internals.DATATYPE_DECIMAL
DATATYPE_DATETIME = _internals.DATATYPE_DATETIME
DATATYPE_ENUMERATION = _internals.DATATYPE_ENUMERATION
DATATYPE_SEQUENCE = _internals.DATATYPE_SEQUENCE
DATATYPE_CHOICE = _internals.DATATYPE_CHOICE
DATATYPE_CORRELATION_ID = _internals.DATATYPE_CORRELATION_ID
blpapi_Logging_SEVERITY_OFF = _internals.blpapi_Logging_SEVERITY_OFF
blpapi_Logging_SEVERITY_FATAL = _internals.blpapi_Logging_SEVERITY_FATAL
blpapi_Logging_SEVERITY_ERROR = _internals.blpapi_Logging_SEVERITY_ERROR
blpapi_Logging_SEVERITY_WARN = _internals.blpapi_Logging_SEVERITY_WARN
blpapi_Logging_SEVERITY_INFO = _internals.blpapi_Logging_SEVERITY_INFO
blpapi_Logging_SEVERITY_DEBUG = _internals.blpapi_Logging_SEVERITY_DEBUG
blpapi_Logging_SEVERITY_TRACE = _internals.blpapi_Logging_SEVERITY_TRACE

def setLoggerCallbackWrapper(cb, severity):
    return _internals.setLoggerCallbackWrapper(cb, severity)

def blpapi_HighPrecisionDatetime_fromTimePoint_wrapper(original):
    return _internals.blpapi_HighPrecisionDatetime_fromTimePoint_wrapper(original)

def blpapi_Logging_registerCallback(callback, thresholdSeverity):
    return _internals.blpapi_Logging_registerCallback(callback, thresholdSeverity)

def blpapi_Logging_logTestMessage(severity):
    return _internals.blpapi_Logging_logTestMessage(severity)

def blpapi_DiagnosticsUtil_memoryInfo_wrapper():
    return _internals.blpapi_DiagnosticsUtil_memoryInfo_wrapper()

def blpapi_EventDispatcher_stop(handle, asynch):
    return _internals.blpapi_EventDispatcher_stop(handle, asynch)

def blpapi_Service_printHelper(service, level, spacesPerLevel):
    return _internals.blpapi_Service_printHelper(service, level, spacesPerLevel)

def blpapi_SchemaElementDefinition_printHelper(item, level, spacesPerLevel):
    return _internals.blpapi_SchemaElementDefinition_printHelper(item, level, spacesPerLevel)

def blpapi_SchemaTypeDefinition_printHelper(item, level, spacesPerLevel):
    return _internals.blpapi_SchemaTypeDefinition_printHelper(item, level, spacesPerLevel)

def blpapi_Message_printHelper(message, level, spacesPerLevel):
    return _internals.blpapi_Message_printHelper(message, level, spacesPerLevel)

def blpapi_SessionOptions_printHelper(sessionOptions, level, spacesPerLevel):
    return _internals.blpapi_SessionOptions_printHelper(sessionOptions, level, spacesPerLevel)

def blpapi_TestUtil_serializeServiceHelper(service):
    return _internals.blpapi_TestUtil_serializeServiceHelper(service)

def blpapi_SchemaTypeDefinition_hasElementDefinition(type, nameString, name):
    return _internals.blpapi_SchemaTypeDefinition_hasElementDefinition(type, nameString, name)

def blpapi_ConstantList_hasConstant(list, nameString, name):
    return _internals.blpapi_ConstantList_hasConstant(list, nameString, name)

def blpapi_Service_hasEventDefinition(service, nameString, name):
    return _internals.blpapi_Service_hasEventDefinition(service, nameString, name)

def blpapi_Service_hasOperation(service, nameString, name):
    return _internals.blpapi_Service_hasOperation(service, nameString, name)

def blpapi_SubscriptionList_addHelper(list, topic, correlationId, fields, options):
    return _internals.blpapi_SubscriptionList_addHelper(list, topic, correlationId, fields, options)

def blpapi_Name_hasName(nameString):
    return _internals.blpapi_Name_hasName(nameString)

def blpapi_TopicList_createFromResolutionList(_from):
    return _internals.blpapi_TopicList_createFromResolutionList(_from)
class intArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _internals.intArray_swiginit(self, _internals.new_intArray(nelements))
    __swig_destroy__ = _internals.delete_intArray

    def __getitem__(self, index):
        return _internals.intArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _internals.intArray___setitem__(self, index, value)

    def cast(self):
        return _internals.intArray_cast(self)

    @staticmethod
    def frompointer(t):
        return _internals.intArray_frompointer(t)

# Register intArray in _internals:
_internals.intArray_swigregister(intArray)

def intArray_frompointer(t):
    return _internals.intArray_frompointer(t)


def new_topicPtrArray(nelements):
    return _internals.new_topicPtrArray(nelements)

def delete_topicPtrArray(ary):
    return _internals.delete_topicPtrArray(ary)

def topicPtrArray_getitem(ary, index):
    return _internals.topicPtrArray_getitem(ary, index)

def topicPtrArray_setitem(ary, index, value):
    return _internals.topicPtrArray_setitem(ary, index, value)

def CorrelationId_t_equals(cid1, cid2):
    return _internals.CorrelationId_t_equals(cid1, cid2)
class CorrelationId(object):
    r"""
    A key used to identify individual subscriptions or requests.

    Two :class:`CorrelationId` objects are considered equal if they have the same
    :meth:`type()` and:

    - Hold the same (not just equal!) objects, if the type is :attr:`OBJECT_TYPE`.
    - Hold equal integers, if the type is :attr:`INT_TYPE` or :attr:`AUTOGEN_TYPE`.

    If the type is :attr:`UNSET_TYPE`, then the two :class:`CorrelationId` objects
    are always equal (as the value of both will necessarily be ``None``).

    It is possible that a user constructed :class:`CorrelationId` and a
    :class:`CorrelationId` generated by the API could return the same result for
    :meth:`value()`. However, they will not compare equal because they have a
    different :meth:`type()`.

    :class:`CorrelationId` objects are passed to many of the :class:`Session`
    object methods which initiate asynchronous operations and are obtained from
    :class:`Message` objects which are delivered as a result of those asynchronous
    operations.

    When subscribing or requesting information, an application has the choice of
    providing a :class:`CorrelationId` they construct themselves or allowing the
    session to construct one for them. If the application supplies a
    :class:`CorrelationId`, it must not re-use the value contained in it in another
    :class:`CorrelationId`, whilst the original request or subscription is still
    active.

    The ``xxx_TYPE`` class attributes represent the possible types of
    :class:`CorrelationId`.
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    value = property(_internals.CorrelationId_value_get)

    UNSET_TYPE = _internals.CORRELATION_TYPE_UNSET
    """The :class:`CorrelationId` is unset. That is, it was created by the
    default :class:`CorrelationId` constructor."""

    INT_TYPE = _internals.CORRELATION_TYPE_INT
    """The :class:`CorrelationId` was created from an :class:`int` or
    :class:`long` supplied by the user."""

    OBJECT_TYPE = _internals.CORRELATION_TYPE_POINTER
    """The :class:`CorrelationId` was created from an object supplied by
    the user."""

    AUTOGEN_TYPE = _internals.CORRELATION_TYPE_AUTOGEN
    """The :class:`CorrelationId` was created internally by API."""

    MAX_CLASS_ID = _internals.CORRELATION_MAX_CLASS_ID
    """The maximum value allowed for ``classId``."""

    __TYPE_NAMES = {
        _internals.CORRELATION_TYPE_UNSET: "UNSET",
        _internals.CORRELATION_TYPE_INT: "INTEGER",
        _internals.CORRELATION_TYPE_POINTER: "OBJECT",
        _internals.CORRELATION_TYPE_AUTOGEN: "AUTOGEN"
    }

    def __str__(self):
        """x.__str__() <==> str(x)"""
        valueType = self.type()
        valueTypeName = CorrelationId.__TYPE_NAMES[valueType]

        if valueType == CorrelationId.UNSET_TYPE:
            return valueTypeName
        else:
            return "({0}: {1!r}, ClassId: {2})".format(
                valueTypeName, self.value(), self.classId())

    def __hash__(self):
        return hash((self.type(), self.classId(), self.__toInteger()))

    def __eq__(self, other):
        """x.__eq__(y) <==> x==y"""
        try:
            return bool(CorrelationId_t_equals(self, other))
        except Exception:
            return NotImplemented

    def __ne__(self, other):
        """x.__ne__(y) <==> x!=y"""
        equal = self.__eq__(other)
        return NotImplemented if equal is NotImplemented else not equal

    def value(self):
        """
        Returns:
            int or long or object: The value of this CorrelationId object.

        The return value depends on this :class:`CorrelationId`\ 's value
        type and could be:

        - Integer (``type() == CorrelationId.INT_TYPE``
          or ``type() == CorrelationId.AUTOGEN_TYPE``)
        - Object (``type() == CorrelationId.OBJECT_TYPE``)
        - ``None`` (``type() == CorrelationId.UNSET_TYPE``)
        """
        valueType = self.type()
        if valueType == CorrelationId.INT_TYPE \
                or valueType == CorrelationId.AUTOGEN_TYPE:
            return self.__asInteger()
        elif valueType == CorrelationId.OBJECT_TYPE:
            return self.__asObject()
        else:
            return None

    def _handle(self):
        return self


    def __init__(self, *args):
        r"""
        ``CorrelationId([value[, classId=0]])`` constructs a :class:`CorrelationId`
        object.

        If ``value`` is an integer (either :class:`int` or :class:`long`) then the
        created :class:`CorrelationId` will have type :attr:`INT_TYPE`. Otherwise, it
        will have type :attr:`OBJECT_TYPE`.

        If no arguments are specified, then the type will be :attr:`UNSET_TYPE`.

        The maximum allowed ``classId`` value is :attr:`MAX_CLASS_ID`.
        """
        _internals.CorrelationId_swiginit(self, _internals.new_CorrelationId(*args))
    __swig_destroy__ = _internals.delete_CorrelationId

    def type(self):
        r"""
        Returns:
            int: The type of this CorrelationId object (see the ``xxx_TYPE`` class
            attributes)
        """
        return _internals.CorrelationId_type(self)

    def classId(self):
        r"""
        Returns:
            int: The user defined classification of this :class:`CorrelationId`
            object
        """
        return _internals.CorrelationId_classId(self)

    def __asObject(self):
        return _internals.CorrelationId___asObject(self)

    def __asInteger(self):
        return _internals.CorrelationId___asInteger(self)

    def __toInteger(self):
        return _internals.CorrelationId___toInteger(self)

# Register CorrelationId in _internals:
_internals.CorrelationId_swigregister(CorrelationId)

class blpapi_CorrelationId_t__value(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _internals.blpapi_CorrelationId_t__value_swiginit(self, _internals.new_blpapi_CorrelationId_t__value())
    __swig_destroy__ = _internals.delete_blpapi_CorrelationId_t__value

# Register blpapi_CorrelationId_t__value in _internals:
_internals.blpapi_CorrelationId_t__value_swigregister(blpapi_CorrelationId_t__value)


def blpapi_Element_toPy(element):
    return _internals.blpapi_Element_toPy(element)

def blpapi_Element_setElementFloat(element, nameString, name, value):
    return _internals.blpapi_Element_setElementFloat(element, nameString, name, value)

def blpapi_Element_setValueFloat(element, value, index):
    return _internals.blpapi_Element_setValueFloat(element, value, index)

def blpapi_Element_printHelper(element, level, spacesPerLevel):
    return _internals.blpapi_Element_printHelper(element, level, spacesPerLevel)

def blpapi_Element_name(element):
    return _internals.blpapi_Element_name(element)

def blpapi_Element_nameString(element):
    return _internals.blpapi_Element_nameString(element)

def blpapi_Element_definition(element):
    return _internals.blpapi_Element_definition(element)

def blpapi_Element_datatype(element):
    return _internals.blpapi_Element_datatype(element)

def blpapi_Element_isComplexType(element):
    return _internals.blpapi_Element_isComplexType(element)

def blpapi_Element_isArray(element):
    return _internals.blpapi_Element_isArray(element)

def blpapi_Element_isReadOnly(element):
    return _internals.blpapi_Element_isReadOnly(element)

def blpapi_Element_numValues(element):
    return _internals.blpapi_Element_numValues(element)

def blpapi_Element_numElements(element):
    return _internals.blpapi_Element_numElements(element)

def blpapi_Element_isNullValue(element, position):
    return _internals.blpapi_Element_isNullValue(element, position)

def blpapi_Element_isNull(element):
    return _internals.blpapi_Element_isNull(element)

def blpapi_Element_getElementAt(element, position):
    return _internals.blpapi_Element_getElementAt(element, position)

def blpapi_Element_getElement(element, nameString, name):
    return _internals.blpapi_Element_getElement(element, nameString, name)

def blpapi_Element_hasElementEx(element, nameString, name, excludeNullElements, reserved):
    return _internals.blpapi_Element_hasElementEx(element, nameString, name, excludeNullElements, reserved)

def blpapi_Element_getValueAsBool(element, index):
    return _internals.blpapi_Element_getValueAsBool(element, index)

def blpapi_Element_getValueAsChar(element, index):
    return _internals.blpapi_Element_getValueAsChar(element, index)

def blpapi_Element_getValueAsInt32(element, index):
    return _internals.blpapi_Element_getValueAsInt32(element, index)

def blpapi_Element_getValueAsInt64(element, index):
    return _internals.blpapi_Element_getValueAsInt64(element, index)

def blpapi_Element_getValueAsFloat64(element, index):
    return _internals.blpapi_Element_getValueAsFloat64(element, index)

def blpapi_Element_getValueAsString(element, index):
    return _internals.blpapi_Element_getValueAsString(element, index)

def blpapi_Element_getValueAsDatetime(element, index):
    return _internals.blpapi_Element_getValueAsDatetime(element, index)

def blpapi_Element_getValueAsHighPrecisionDatetime(element, index):
    return _internals.blpapi_Element_getValueAsHighPrecisionDatetime(element, index)

def blpapi_Element_getValueAsElement(element, index):
    return _internals.blpapi_Element_getValueAsElement(element, index)

def blpapi_Element_getValueAsName(element, index):
    return _internals.blpapi_Element_getValueAsName(element, index)

def blpapi_Element_getChoice(element):
    return _internals.blpapi_Element_getChoice(element)

def blpapi_Element_setValueBool(element, value, index):
    return _internals.blpapi_Element_setValueBool(element, value, index)

def blpapi_Element_setValueInt32(element, value, index):
    return _internals.blpapi_Element_setValueInt32(element, value, index)

def blpapi_Element_setValueInt64(element, value, index):
    return _internals.blpapi_Element_setValueInt64(element, value, index)

def blpapi_Element_setValueString(element, value, index):
    return _internals.blpapi_Element_setValueString(element, value, index)

def blpapi_Element_setValueHighPrecisionDatetime(element, value, index):
    return _internals.blpapi_Element_setValueHighPrecisionDatetime(element, value, index)

def blpapi_Element_setValueFromName(element, value, index):
    return _internals.blpapi_Element_setValueFromName(element, value, index)

def blpapi_Element_setElementBool(element, nameString, name, value):
    return _internals.blpapi_Element_setElementBool(element, nameString, name, value)

def blpapi_Element_setElementInt32(element, nameString, name, value):
    return _internals.blpapi_Element_setElementInt32(element, nameString, name, value)

def blpapi_Element_setElementInt64(element, nameString, name, value):
    return _internals.blpapi_Element_setElementInt64(element, nameString, name, value)

def blpapi_Element_setElementString(element, nameString, name, value):
    return _internals.blpapi_Element_setElementString(element, nameString, name, value)

def blpapi_Element_setElementHighPrecisionDatetime(element, nameString, name, value):
    return _internals.blpapi_Element_setElementHighPrecisionDatetime(element, nameString, name, value)

def blpapi_Element_setElementFromName(element, elementName, name, buffer):
    return _internals.blpapi_Element_setElementFromName(element, elementName, name, buffer)

def blpapi_Element_appendElement(element):
    return _internals.blpapi_Element_appendElement(element)

def blpapi_Element_setChoice(element, nameCstr, name, index):
    return _internals.blpapi_Element_setChoice(element, nameCstr, name, index)

def blpapi_EventFormatter_setValueFloat(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueFloat(formatter, typeString, typeName, value)

def blpapi_EventFormatter_appendValueFloat(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueFloat(formatter, value)

def blpapi_EventFormatter_create(event):
    return _internals.blpapi_EventFormatter_create(event)

def blpapi_EventFormatter_destroy(victim):
    return _internals.blpapi_EventFormatter_destroy(victim)

def blpapi_EventFormatter_appendMessage(formatter, typeString, typeName, topic):
    return _internals.blpapi_EventFormatter_appendMessage(formatter, typeString, typeName, topic)

def blpapi_EventFormatter_appendMessageSeq(formatter, typeString, typeName, topic, sequenceNumber, arg6):
    return _internals.blpapi_EventFormatter_appendMessageSeq(formatter, typeString, typeName, topic, sequenceNumber, arg6)

def blpapi_EventFormatter_appendResponse(formatter, typeString, typeName):
    return _internals.blpapi_EventFormatter_appendResponse(formatter, typeString, typeName)

def blpapi_EventFormatter_appendRecapMessage(formatter, topic, cid):
    return _internals.blpapi_EventFormatter_appendRecapMessage(formatter, topic, cid)

def blpapi_EventFormatter_appendRecapMessageSeq(formatter, topic, cid, sequenceNumber, arg5):
    return _internals.blpapi_EventFormatter_appendRecapMessageSeq(formatter, topic, cid, sequenceNumber, arg5)

def blpapi_EventFormatter_appendFragmentedRecapMessage(formatter, typeString, typeName, topic, cid, fragmentType):
    return _internals.blpapi_EventFormatter_appendFragmentedRecapMessage(formatter, typeString, typeName, topic, cid, fragmentType)

def blpapi_EventFormatter_appendFragmentedRecapMessageSeq(formatter, typeString, typeName, topic, fragmentType, sequenceNumber):
    return _internals.blpapi_EventFormatter_appendFragmentedRecapMessageSeq(formatter, typeString, typeName, topic, fragmentType, sequenceNumber)

def blpapi_EventFormatter_setValueBool(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueBool(formatter, typeString, typeName, value)

def blpapi_EventFormatter_setValueChar(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueChar(formatter, typeString, typeName, value)

def blpapi_EventFormatter_setValueInt32(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueInt32(formatter, typeString, typeName, value)

def blpapi_EventFormatter_setValueInt64(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueInt64(formatter, typeString, typeName, value)

def blpapi_EventFormatter_setValueHighPrecisionDatetime(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueHighPrecisionDatetime(formatter, typeString, typeName, value)

def blpapi_EventFormatter_setValueString(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueString(formatter, typeString, typeName, value)

def blpapi_EventFormatter_setValueFromName(formatter, typeString, typeName, value):
    return _internals.blpapi_EventFormatter_setValueFromName(formatter, typeString, typeName, value)

def blpapi_EventFormatter_setValueNull(formatter, typeString, typeName):
    return _internals.blpapi_EventFormatter_setValueNull(formatter, typeString, typeName)

def blpapi_EventFormatter_pushElement(formatter, typeString, typeName):
    return _internals.blpapi_EventFormatter_pushElement(formatter, typeString, typeName)

def blpapi_EventFormatter_popElement(formatter):
    return _internals.blpapi_EventFormatter_popElement(formatter)

def blpapi_EventFormatter_appendValueBool(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueBool(formatter, value)

def blpapi_EventFormatter_appendValueChar(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueChar(formatter, value)

def blpapi_EventFormatter_appendValueInt32(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueInt32(formatter, value)

def blpapi_EventFormatter_appendValueInt64(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueInt64(formatter, value)

def blpapi_EventFormatter_appendValueHighPrecisionDatetime(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueHighPrecisionDatetime(formatter, value)

def blpapi_EventFormatter_appendValueString(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueString(formatter, value)

def blpapi_EventFormatter_appendValueFromName(formatter, value):
    return _internals.blpapi_EventFormatter_appendValueFromName(formatter, value)

def blpapi_EventFormatter_appendElement(formatter):
    return _internals.blpapi_EventFormatter_appendElement(formatter)

def Session_createHelper(parameters, eventHandlerFunc, dispatcher):
    return _internals.Session_createHelper(parameters, eventHandlerFunc, dispatcher)

def Session_destroyHelper(sessionHandle, eventHandlerFunc):
    return _internals.Session_destroyHelper(sessionHandle, eventHandlerFunc)

def blpapi_EventDispatcher_create(numDispatcherThreads):
    return _internals.blpapi_EventDispatcher_create(numDispatcherThreads)

def blpapi_EventDispatcher_destroy(handle):
    return _internals.blpapi_EventDispatcher_destroy(handle)

def blpapi_EventDispatcher_start(handle):
    return _internals.blpapi_EventDispatcher_start(handle)

def ProviderSession_createHelper(parameters, eventHandlerFunc, dispatcher):
    return _internals.ProviderSession_createHelper(parameters, eventHandlerFunc, dispatcher)

def ProviderSession_destroyHelper(sessionHandle, eventHandlerFunc):
    return _internals.ProviderSession_destroyHelper(sessionHandle, eventHandlerFunc)

def ProviderSession_terminateSubscriptionsOnTopic(sessionHandle, topic, message):
    return _internals.ProviderSession_terminateSubscriptionsOnTopic(sessionHandle, topic, message)

def blpapi_MessageFormatter_setValueFloat(formatter, typeName, value):
    return _internals.blpapi_MessageFormatter_setValueFloat(formatter, typeName, value)

def blpapi_MessageFormatter_appendValueFloat(formatter, value):
    return _internals.blpapi_MessageFormatter_appendValueFloat(formatter, value)

def blpapi_MessageFormatter_setValueBool(formatter, typeName, value):
    return _internals.blpapi_MessageFormatter_setValueBool(formatter, typeName, value)

def blpapi_MessageFormatter_setValueChar(formatter, typeName, value):
    return _internals.blpapi_MessageFormatter_setValueChar(formatter, typeName, value)

def blpapi_MessageFormatter_setValueInt32(formatter, typeName, value):
    return _internals.blpapi_MessageFormatter_setValueInt32(formatter, typeName, value)

def blpapi_MessageFormatter_setValueInt64(formatter, typeName, value):
    return _internals.blpapi_MessageFormatter_setValueInt64(formatter, typeName, value)

def blpapi_MessageFormatter_setValueFloat32(formatter, typeName, value):
    return _internals.blpapi_MessageFormatter_setValueFloat32(formatter, typeName, value)

def blpapi_MessageFormatter_setValueFloat64(formatter, typeName, value):
    return _internals.blpapi_MessageFormatter_setValueFloat64(formatter, typeName, value)

def blpapi_MessageFormatter_setValueDatetime(formatter, typeName, value):
    return _internals.blpapi_MessageFormatter_setValueDatetime(formatter, typeName, value)

def blpapi_MessageFormatter_setValueHighPrecisionDatetime(formatter, typeName, value):
    return _internals.blpapi_MessageFormatter_setValueHighPrecisionDatetime(formatter, typeName, value)

def blpapi_MessageFormatter_setValueString(formatter, typeName, value):
    return _internals.blpapi_MessageFormatter_setValueString(formatter, typeName, value)

def blpapi_MessageFormatter_setValueFromName(formatter, typeName, value):
    return _internals.blpapi_MessageFormatter_setValueFromName(formatter, typeName, value)

def blpapi_MessageFormatter_setValueNull(formatter, typeName):
    return _internals.blpapi_MessageFormatter_setValueNull(formatter, typeName)

def blpapi_MessageFormatter_pushElement(formatter, typeName):
    return _internals.blpapi_MessageFormatter_pushElement(formatter, typeName)

def blpapi_MessageFormatter_popElement(formatter):
    return _internals.blpapi_MessageFormatter_popElement(formatter)

def blpapi_MessageFormatter_appendValueBool(formatter, value):
    return _internals.blpapi_MessageFormatter_appendValueBool(formatter, value)

def blpapi_MessageFormatter_appendValueChar(formatter, value):
    return _internals.blpapi_MessageFormatter_appendValueChar(formatter, value)

def blpapi_MessageFormatter_appendValueInt32(formatter, value):
    return _internals.blpapi_MessageFormatter_appendValueInt32(formatter, value)

def blpapi_MessageFormatter_appendValueInt64(formatter, value):
    return _internals.blpapi_MessageFormatter_appendValueInt64(formatter, value)

def blpapi_MessageFormatter_appendValueFloat32(formatter, value):
    return _internals.blpapi_MessageFormatter_appendValueFloat32(formatter, value)

def blpapi_MessageFormatter_appendValueFloat64(formatter, value):
    return _internals.blpapi_MessageFormatter_appendValueFloat64(formatter, value)

def blpapi_MessageFormatter_appendValueDatetime(formatter, value):
    return _internals.blpapi_MessageFormatter_appendValueDatetime(formatter, value)

def blpapi_MessageFormatter_appendValueHighPrecisionDatetime(formatter, value):
    return _internals.blpapi_MessageFormatter_appendValueHighPrecisionDatetime(formatter, value)

def blpapi_MessageFormatter_appendValueString(formatter, value):
    return _internals.blpapi_MessageFormatter_appendValueString(formatter, value)

def blpapi_MessageFormatter_appendValueFromName(formatter, value):
    return _internals.blpapi_MessageFormatter_appendValueFromName(formatter, value)

def blpapi_MessageFormatter_appendElement(formatter):
    return _internals.blpapi_MessageFormatter_appendElement(formatter)

def blpapi_MessageFormatter_FormatMessageJson(formatter, message):
    return _internals.blpapi_MessageFormatter_FormatMessageJson(formatter, message)

def blpapi_MessageFormatter_FormatMessageXml(formatter, message):
    return _internals.blpapi_MessageFormatter_FormatMessageXml(formatter, message)

def blpapi_MessageFormatter_copy(original):
    return _internals.blpapi_MessageFormatter_copy(original)

def blpapi_MessageFormatter_assign(rhs):
    return _internals.blpapi_MessageFormatter_assign(rhs)

def blpapi_MessageFormatter_destroy(formatter):
    return _internals.blpapi_MessageFormatter_destroy(formatter)

def blpapi_AuthOptions_create_default():
    return _internals.blpapi_AuthOptions_create_default()

def blpapi_AuthOptions_create_forUserMode(user):
    return _internals.blpapi_AuthOptions_create_forUserMode(user)

def blpapi_AuthOptions_create_forAppMode(app):
    return _internals.blpapi_AuthOptions_create_forAppMode(app)

def blpapi_AuthOptions_create_forUserAndAppMode(user, app):
    return _internals.blpapi_AuthOptions_create_forUserAndAppMode(user, app)

def blpapi_AuthOptions_create_forToken(token):
    return _internals.blpapi_AuthOptions_create_forToken(token)

def blpapi_AuthOptions_duplicate(dup):
    return _internals.blpapi_AuthOptions_duplicate(dup)

def blpapi_AuthOptions_copy(lhs, rhs):
    return _internals.blpapi_AuthOptions_copy(lhs, rhs)

def blpapi_AuthOptions_destroy(options):
    return _internals.blpapi_AuthOptions_destroy(options)

def blpapi_AuthUser_createWithLogonName():
    return _internals.blpapi_AuthUser_createWithLogonName()

def blpapi_AuthUser_createWithActiveDirectoryProperty(propertyName):
    return _internals.blpapi_AuthUser_createWithActiveDirectoryProperty(propertyName)

def blpapi_AuthUser_createWithManualOptions(userId, ipAddress):
    return _internals.blpapi_AuthUser_createWithManualOptions(userId, ipAddress)

def blpapi_AuthUser_duplicate(dup):
    return _internals.blpapi_AuthUser_duplicate(dup)

def blpapi_AuthUser_copy(lhs, rhs):
    return _internals.blpapi_AuthUser_copy(lhs, rhs)

def blpapi_AuthUser_destroy(user):
    return _internals.blpapi_AuthUser_destroy(user)

def blpapi_AuthApplication_create(appName):
    return _internals.blpapi_AuthApplication_create(appName)

def blpapi_AuthApplication_duplicate(dup):
    return _internals.blpapi_AuthApplication_duplicate(dup)

def blpapi_AuthApplication_copy(lhs, rhs):
    return _internals.blpapi_AuthApplication_copy(lhs, rhs)

def blpapi_AuthApplication_destroy(app):
    return _internals.blpapi_AuthApplication_destroy(app)

def blpapi_AuthToken_create(tokenStr):
    return _internals.blpapi_AuthToken_create(tokenStr)

def blpapi_AuthToken_duplicate(dup):
    return _internals.blpapi_AuthToken_duplicate(dup)

def blpapi_AuthToken_copy(lhs, rhs):
    return _internals.blpapi_AuthToken_copy(lhs, rhs)

def blpapi_AuthToken_destroy(token):
    return _internals.blpapi_AuthToken_destroy(token)
UNKNOWN_CLASS = _internals.UNKNOWN_CLASS
INVALIDSTATE_CLASS = _internals.INVALIDSTATE_CLASS
INVALIDARG_CLASS = _internals.INVALIDARG_CLASS
IOERROR_CLASS = _internals.IOERROR_CLASS
CNVERROR_CLASS = _internals.CNVERROR_CLASS
BOUNDSERROR_CLASS = _internals.BOUNDSERROR_CLASS
NOTFOUND_CLASS = _internals.NOTFOUND_CLASS
FLDNOTFOUND_CLASS = _internals.FLDNOTFOUND_CLASS
UNSUPPORTED_CLASS = _internals.UNSUPPORTED_CLASS
ERROR_UNKNOWN = _internals.ERROR_UNKNOWN
ERROR_ILLEGAL_ARG = _internals.ERROR_ILLEGAL_ARG
ERROR_ILLEGAL_ACCESS = _internals.ERROR_ILLEGAL_ACCESS
ERROR_INVALID_SESSION = _internals.ERROR_INVALID_SESSION
ERROR_DUPLICATE_CORRELATIONID = _internals.ERROR_DUPLICATE_CORRELATIONID
ERROR_INTERNAL_ERROR = _internals.ERROR_INTERNAL_ERROR
ERROR_RESOLVE_FAILED = _internals.ERROR_RESOLVE_FAILED
ERROR_CONNECT_FAILED = _internals.ERROR_CONNECT_FAILED
ERROR_ILLEGAL_STATE = _internals.ERROR_ILLEGAL_STATE
ERROR_CODEC_FAILURE = _internals.ERROR_CODEC_FAILURE
ERROR_INDEX_OUT_OF_RANGE = _internals.ERROR_INDEX_OUT_OF_RANGE
ERROR_INVALID_CONVERSION = _internals.ERROR_INVALID_CONVERSION
ERROR_ITEM_NOT_FOUND = _internals.ERROR_ITEM_NOT_FOUND
ERROR_IO_ERROR = _internals.ERROR_IO_ERROR
ERROR_CORRELATION_NOT_FOUND = _internals.ERROR_CORRELATION_NOT_FOUND
ERROR_SERVICE_NOT_FOUND = _internals.ERROR_SERVICE_NOT_FOUND
ERROR_LOGON_LOOKUP_FAILED = _internals.ERROR_LOGON_LOOKUP_FAILED
ERROR_DS_LOOKUP_FAILED = _internals.ERROR_DS_LOOKUP_FAILED
ERROR_UNSUPPORTED_OPERATION = _internals.ERROR_UNSUPPORTED_OPERATION
ERROR_DS_PROPERTY_NOT_FOUND = _internals.ERROR_DS_PROPERTY_NOT_FOUND
ERROR_MSG_TOO_LARGE = _internals.ERROR_MSG_TOO_LARGE

def blpapi_getLastErrorDescription(resultCode):
    return _internals.blpapi_getLastErrorDescription(resultCode)

def blpapi_SessionOptions_create():
    return _internals.blpapi_SessionOptions_create()

def blpapi_SessionOptions_destroy(parameters):
    return _internals.blpapi_SessionOptions_destroy(parameters)

def blpapi_SessionOptions_setServerHost(parameters, serverHost):
    return _internals.blpapi_SessionOptions_setServerHost(parameters, serverHost)

def blpapi_SessionOptions_setServerPort(parameters, serverPort):
    return _internals.blpapi_SessionOptions_setServerPort(parameters, serverPort)

def blpapi_SessionOptions_setServerAddress(parameters, serverHost, serverPort, index):
    return _internals.blpapi_SessionOptions_setServerAddress(parameters, serverHost, serverPort, index)

def blpapi_SessionOptions_removeServerAddress(parameters, index):
    return _internals.blpapi_SessionOptions_removeServerAddress(parameters, index)

def blpapi_SessionOptions_setConnectTimeout(parameters, timeoutInMilliseconds):
    return _internals.blpapi_SessionOptions_setConnectTimeout(parameters, timeoutInMilliseconds)

def blpapi_SessionOptions_setDefaultServices(parameters, defaultServices):
    return _internals.blpapi_SessionOptions_setDefaultServices(parameters, defaultServices)

def blpapi_SessionOptions_setDefaultSubscriptionService(parameters, serviceIdentifier):
    return _internals.blpapi_SessionOptions_setDefaultSubscriptionService(parameters, serviceIdentifier)

def blpapi_SessionOptions_setDefaultTopicPrefix(parameters, prefix):
    return _internals.blpapi_SessionOptions_setDefaultTopicPrefix(parameters, prefix)

def blpapi_SessionOptions_setAllowMultipleCorrelatorsPerMsg(parameters, allowMultipleCorrelatorsPerMsg):
    return _internals.blpapi_SessionOptions_setAllowMultipleCorrelatorsPerMsg(parameters, allowMultipleCorrelatorsPerMsg)

def blpapi_SessionOptions_setClientMode(parameters, clientMode):
    return _internals.blpapi_SessionOptions_setClientMode(parameters, clientMode)

def blpapi_SessionOptions_setMaxPendingRequests(parameters, maxPendingRequests):
    return _internals.blpapi_SessionOptions_setMaxPendingRequests(parameters, maxPendingRequests)

def blpapi_SessionOptions_setAutoRestartOnDisconnection(parameters, autoRestart):
    return _internals.blpapi_SessionOptions_setAutoRestartOnDisconnection(parameters, autoRestart)

def blpapi_SessionOptions_setSessionIdentityOptions(parameters, authOptions, cid):
    return _internals.blpapi_SessionOptions_setSessionIdentityOptions(parameters, authOptions, cid)

def blpapi_SessionOptions_setAuthenticationOptions(parameters, authOptions):
    return _internals.blpapi_SessionOptions_setAuthenticationOptions(parameters, authOptions)

def blpapi_SessionOptions_setNumStartAttempts(parameters, numStartAttempts):
    return _internals.blpapi_SessionOptions_setNumStartAttempts(parameters, numStartAttempts)

def blpapi_SessionOptions_setMaxEventQueueSize(parameters, maxEventQueueSize):
    return _internals.blpapi_SessionOptions_setMaxEventQueueSize(parameters, maxEventQueueSize)

def blpapi_SessionOptions_setSlowConsumerWarningHiWaterMark(parameters, hiWaterMark):
    return _internals.blpapi_SessionOptions_setSlowConsumerWarningHiWaterMark(parameters, hiWaterMark)

def blpapi_SessionOptions_setSlowConsumerWarningLoWaterMark(parameters, loWaterMark):
    return _internals.blpapi_SessionOptions_setSlowConsumerWarningLoWaterMark(parameters, loWaterMark)

def blpapi_SessionOptions_setDefaultKeepAliveInactivityTime(parameters, inactivityMsecs):
    return _internals.blpapi_SessionOptions_setDefaultKeepAliveInactivityTime(parameters, inactivityMsecs)

def blpapi_SessionOptions_setDefaultKeepAliveResponseTimeout(parameters, timeoutMsecs):
    return _internals.blpapi_SessionOptions_setDefaultKeepAliveResponseTimeout(parameters, timeoutMsecs)

def blpapi_SessionOptions_setKeepAliveEnabled(parameters, isEnabled):
    return _internals.blpapi_SessionOptions_setKeepAliveEnabled(parameters, isEnabled)

def blpapi_SessionOptions_setRecordSubscriptionDataReceiveTimes(parameters, shouldRecord):
    return _internals.blpapi_SessionOptions_setRecordSubscriptionDataReceiveTimes(parameters, shouldRecord)

def blpapi_SessionOptions_setServiceCheckTimeout(paramaters, timeoutMsecs):
    return _internals.blpapi_SessionOptions_setServiceCheckTimeout(paramaters, timeoutMsecs)

def blpapi_SessionOptions_setServiceDownloadTimeout(paramaters, timeoutMsecs):
    return _internals.blpapi_SessionOptions_setServiceDownloadTimeout(paramaters, timeoutMsecs)

def blpapi_SessionOptions_setTlsOptions(paramaters, tlsOptions):
    return _internals.blpapi_SessionOptions_setTlsOptions(paramaters, tlsOptions)

def blpapi_SessionOptions_setFlushPublishedEventsTimeout(paramaters, timeoutMsecs):
    return _internals.blpapi_SessionOptions_setFlushPublishedEventsTimeout(paramaters, timeoutMsecs)

def blpapi_SessionOptions_setBandwidthSaveModeDisabled(parameters, disableBandwidthSaveMode):
    return _internals.blpapi_SessionOptions_setBandwidthSaveModeDisabled(parameters, disableBandwidthSaveMode)

def blpapi_SessionOptions_serverHost(parameters):
    return _internals.blpapi_SessionOptions_serverHost(parameters)

def blpapi_SessionOptions_serverPort(parameters):
    return _internals.blpapi_SessionOptions_serverPort(parameters)

def blpapi_SessionOptions_numServerAddresses(parameters):
    return _internals.blpapi_SessionOptions_numServerAddresses(parameters)

def blpapi_SessionOptions_getServerAddress(parameters, index):
    return _internals.blpapi_SessionOptions_getServerAddress(parameters, index)

def blpapi_SessionOptions_connectTimeout(parameters):
    return _internals.blpapi_SessionOptions_connectTimeout(parameters)

def blpapi_SessionOptions_defaultServices(parameters):
    return _internals.blpapi_SessionOptions_defaultServices(parameters)

def blpapi_SessionOptions_defaultSubscriptionService(parameters):
    return _internals.blpapi_SessionOptions_defaultSubscriptionService(parameters)

def blpapi_SessionOptions_defaultTopicPrefix(parameters):
    return _internals.blpapi_SessionOptions_defaultTopicPrefix(parameters)

def blpapi_SessionOptions_allowMultipleCorrelatorsPerMsg(parameters):
    return _internals.blpapi_SessionOptions_allowMultipleCorrelatorsPerMsg(parameters)

def blpapi_SessionOptions_clientMode(parameters):
    return _internals.blpapi_SessionOptions_clientMode(parameters)

def blpapi_SessionOptions_maxPendingRequests(parameters):
    return _internals.blpapi_SessionOptions_maxPendingRequests(parameters)

def blpapi_SessionOptions_autoRestartOnDisconnection(parameters):
    return _internals.blpapi_SessionOptions_autoRestartOnDisconnection(parameters)

def blpapi_SessionOptions_authenticationOptions(parameters):
    return _internals.blpapi_SessionOptions_authenticationOptions(parameters)

def blpapi_SessionOptions_numStartAttempts(parameters):
    return _internals.blpapi_SessionOptions_numStartAttempts(parameters)

def blpapi_SessionOptions_maxEventQueueSize(parameters):
    return _internals.blpapi_SessionOptions_maxEventQueueSize(parameters)

def blpapi_SessionOptions_slowConsumerWarningHiWaterMark(parameters):
    return _internals.blpapi_SessionOptions_slowConsumerWarningHiWaterMark(parameters)

def blpapi_SessionOptions_slowConsumerWarningLoWaterMark(parameters):
    return _internals.blpapi_SessionOptions_slowConsumerWarningLoWaterMark(parameters)

def blpapi_SessionOptions_defaultKeepAliveInactivityTime(parameters):
    return _internals.blpapi_SessionOptions_defaultKeepAliveInactivityTime(parameters)

def blpapi_SessionOptions_defaultKeepAliveResponseTimeout(parameters):
    return _internals.blpapi_SessionOptions_defaultKeepAliveResponseTimeout(parameters)

def blpapi_SessionOptions_keepAliveEnabled(parameters):
    return _internals.blpapi_SessionOptions_keepAliveEnabled(parameters)

def blpapi_SessionOptions_recordSubscriptionDataReceiveTimes(parameters):
    return _internals.blpapi_SessionOptions_recordSubscriptionDataReceiveTimes(parameters)

def blpapi_SessionOptions_serviceCheckTimeout(parameters):
    return _internals.blpapi_SessionOptions_serviceCheckTimeout(parameters)

def blpapi_SessionOptions_serviceDownloadTimeout(parameters):
    return _internals.blpapi_SessionOptions_serviceDownloadTimeout(parameters)

def blpapi_SessionOptions_flushPublishedEventsTimeout(parameters):
    return _internals.blpapi_SessionOptions_flushPublishedEventsTimeout(parameters)

def blpapi_SessionOptions_bandwidthSaveModeDisabled(parameters):
    return _internals.blpapi_SessionOptions_bandwidthSaveModeDisabled(parameters)

def blpapi_TlsOptions_destroy(parameters):
    return _internals.blpapi_TlsOptions_destroy(parameters)

def blpapi_TlsOptions_createFromFiles(clientCredentialsFileName, clientCredentialsPassword, trustedCertificatesFileName):
    return _internals.blpapi_TlsOptions_createFromFiles(clientCredentialsFileName, clientCredentialsPassword, trustedCertificatesFileName)

def blpapi_TlsOptions_createFromBlobs(clientCredentialsRawData, clientCredentialsPassword, trustedCertificatesRawData):
    return _internals.blpapi_TlsOptions_createFromBlobs(clientCredentialsRawData, clientCredentialsPassword, trustedCertificatesRawData)

def blpapi_TlsOptions_setTlsHandshakeTimeoutMs(paramaters, tlsHandshakeTimeoutMs):
    return _internals.blpapi_TlsOptions_setTlsHandshakeTimeoutMs(paramaters, tlsHandshakeTimeoutMs)

def blpapi_TlsOptions_setCrlFetchTimeoutMs(paramaters, crlFetchTimeoutMs):
    return _internals.blpapi_TlsOptions_setCrlFetchTimeoutMs(paramaters, crlFetchTimeoutMs)

def blpapi_Name_create(nameString):
    return _internals.blpapi_Name_create(nameString)

def blpapi_Name_destroy(name):
    return _internals.blpapi_Name_destroy(name)

def blpapi_Name_equalsStr(name, string):
    return _internals.blpapi_Name_equalsStr(name, string)

def blpapi_Name_string(name):
    return _internals.blpapi_Name_string(name)

def blpapi_Name_length(name):
    return _internals.blpapi_Name_length(name)

def blpapi_Name_findName(nameString):
    return _internals.blpapi_Name_findName(nameString)

def blpapi_SubscriptionList_create():
    return _internals.blpapi_SubscriptionList_create()

def blpapi_SubscriptionList_destroy(list):
    return _internals.blpapi_SubscriptionList_destroy(list)

def blpapi_SubscriptionList_addResolved(list, subscriptionString, correlationId):
    return _internals.blpapi_SubscriptionList_addResolved(list, subscriptionString, correlationId)

def blpapi_SubscriptionList_clear(list):
    return _internals.blpapi_SubscriptionList_clear(list)

def blpapi_SubscriptionList_append(dest, src):
    return _internals.blpapi_SubscriptionList_append(dest, src)

def blpapi_SubscriptionList_size(list):
    return _internals.blpapi_SubscriptionList_size(list)

def blpapi_SubscriptionList_correlationIdAt(list, index):
    return _internals.blpapi_SubscriptionList_correlationIdAt(list, index)

def blpapi_SubscriptionList_topicStringAt(list, index):
    return _internals.blpapi_SubscriptionList_topicStringAt(list, index)

def blpapi_SubscriptionList_isResolvedAt(list, index):
    return _internals.blpapi_SubscriptionList_isResolvedAt(list, index)
class blpapi_TimePoint(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    d_value = property(_internals.blpapi_TimePoint_d_value_get, _internals.blpapi_TimePoint_d_value_set)

    def __init__(self):
        _internals.blpapi_TimePoint_swiginit(self, _internals.new_blpapi_TimePoint())
    __swig_destroy__ = _internals.delete_blpapi_TimePoint

# Register blpapi_TimePoint in _internals:
_internals.blpapi_TimePoint_swigregister(blpapi_TimePoint)


def blpapi_TimePointUtil_nanosecondsBetween(start, end):
    return _internals.blpapi_TimePointUtil_nanosecondsBetween(start, end)
class blpapi_Datetime_tag(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    parts = property(_internals.blpapi_Datetime_tag_parts_get, _internals.blpapi_Datetime_tag_parts_set)
    hours = property(_internals.blpapi_Datetime_tag_hours_get, _internals.blpapi_Datetime_tag_hours_set)
    minutes = property(_internals.blpapi_Datetime_tag_minutes_get, _internals.blpapi_Datetime_tag_minutes_set)
    seconds = property(_internals.blpapi_Datetime_tag_seconds_get, _internals.blpapi_Datetime_tag_seconds_set)
    milliSeconds = property(_internals.blpapi_Datetime_tag_milliSeconds_get, _internals.blpapi_Datetime_tag_milliSeconds_set)
    month = property(_internals.blpapi_Datetime_tag_month_get, _internals.blpapi_Datetime_tag_month_set)
    day = property(_internals.blpapi_Datetime_tag_day_get, _internals.blpapi_Datetime_tag_day_set)
    year = property(_internals.blpapi_Datetime_tag_year_get, _internals.blpapi_Datetime_tag_year_set)
    offset = property(_internals.blpapi_Datetime_tag_offset_get, _internals.blpapi_Datetime_tag_offset_set)

    def __init__(self):
        _internals.blpapi_Datetime_tag_swiginit(self, _internals.new_blpapi_Datetime_tag())
    __swig_destroy__ = _internals.delete_blpapi_Datetime_tag

# Register blpapi_Datetime_tag in _internals:
_internals.blpapi_Datetime_tag_swigregister(blpapi_Datetime_tag)

class blpapi_HighPrecisionDatetime_tag(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    datetime = property(_internals.blpapi_HighPrecisionDatetime_tag_datetime_get, _internals.blpapi_HighPrecisionDatetime_tag_datetime_set)
    picoseconds = property(_internals.blpapi_HighPrecisionDatetime_tag_picoseconds_get, _internals.blpapi_HighPrecisionDatetime_tag_picoseconds_set)

    def __init__(self):
        _internals.blpapi_HighPrecisionDatetime_tag_swiginit(self, _internals.new_blpapi_HighPrecisionDatetime_tag())
    __swig_destroy__ = _internals.delete_blpapi_HighPrecisionDatetime_tag

# Register blpapi_HighPrecisionDatetime_tag in _internals:
_internals.blpapi_HighPrecisionDatetime_tag_swigregister(blpapi_HighPrecisionDatetime_tag)


def blpapi_HighPrecisionDatetime_compare(lhs, rhs):
    return _internals.blpapi_HighPrecisionDatetime_compare(lhs, rhs)

def blpapi_HighPrecisionDatetime_print(datetime, streamWriter, stream, level, spacesPerLevel):
    return _internals.blpapi_HighPrecisionDatetime_print(datetime, streamWriter, stream, level, spacesPerLevel)

def blpapi_HighPrecisionDatetime_fromTimePoint(datetime, offset):
    return _internals.blpapi_HighPrecisionDatetime_fromTimePoint(datetime, offset)

def blpapi_Constant_name(constant):
    return _internals.blpapi_Constant_name(constant)

def blpapi_Constant_description(constant):
    return _internals.blpapi_Constant_description(constant)

def blpapi_Constant_status(constant):
    return _internals.blpapi_Constant_status(constant)

def blpapi_Constant_datatype(constant):
    return _internals.blpapi_Constant_datatype(constant)

def blpapi_Constant_getValueAsChar(constant):
    return _internals.blpapi_Constant_getValueAsChar(constant)

def blpapi_Constant_getValueAsInt32(constant):
    return _internals.blpapi_Constant_getValueAsInt32(constant)

def blpapi_Constant_getValueAsInt64(constant):
    return _internals.blpapi_Constant_getValueAsInt64(constant)

def blpapi_Constant_getValueAsFloat32(constant):
    return _internals.blpapi_Constant_getValueAsFloat32(constant)

def blpapi_Constant_getValueAsFloat64(constant):
    return _internals.blpapi_Constant_getValueAsFloat64(constant)

def blpapi_Constant_getValueAsDatetime(constant):
    return _internals.blpapi_Constant_getValueAsDatetime(constant)

def blpapi_Constant_getValueAsString(constant):
    return _internals.blpapi_Constant_getValueAsString(constant)

def blpapi_ConstantList_name(list):
    return _internals.blpapi_ConstantList_name(list)

def blpapi_ConstantList_description(list):
    return _internals.blpapi_ConstantList_description(list)

def blpapi_ConstantList_numConstants(list):
    return _internals.blpapi_ConstantList_numConstants(list)

def blpapi_ConstantList_datatype(constant):
    return _internals.blpapi_ConstantList_datatype(constant)

def blpapi_ConstantList_status(list):
    return _internals.blpapi_ConstantList_status(list)

def blpapi_ConstantList_getConstant(constant, nameString, name):
    return _internals.blpapi_ConstantList_getConstant(constant, nameString, name)

def blpapi_ConstantList_getConstantAt(constant, index):
    return _internals.blpapi_ConstantList_getConstantAt(constant, index)

def blpapi_SchemaElementDefinition_name(field):
    return _internals.blpapi_SchemaElementDefinition_name(field)

def blpapi_SchemaElementDefinition_description(field):
    return _internals.blpapi_SchemaElementDefinition_description(field)

def blpapi_SchemaElementDefinition_status(field):
    return _internals.blpapi_SchemaElementDefinition_status(field)

def blpapi_SchemaElementDefinition_type(field):
    return _internals.blpapi_SchemaElementDefinition_type(field)

def blpapi_SchemaElementDefinition_numAlternateNames(field):
    return _internals.blpapi_SchemaElementDefinition_numAlternateNames(field)

def blpapi_SchemaElementDefinition_getAlternateName(field, index):
    return _internals.blpapi_SchemaElementDefinition_getAlternateName(field, index)

def blpapi_SchemaElementDefinition_minValues(field):
    return _internals.blpapi_SchemaElementDefinition_minValues(field)

def blpapi_SchemaElementDefinition_maxValues(field):
    return _internals.blpapi_SchemaElementDefinition_maxValues(field)

def blpapi_SchemaTypeDefinition_name(type):
    return _internals.blpapi_SchemaTypeDefinition_name(type)

def blpapi_SchemaTypeDefinition_description(type):
    return _internals.blpapi_SchemaTypeDefinition_description(type)

def blpapi_SchemaTypeDefinition_status(type):
    return _internals.blpapi_SchemaTypeDefinition_status(type)

def blpapi_SchemaTypeDefinition_datatype(type):
    return _internals.blpapi_SchemaTypeDefinition_datatype(type)

def blpapi_SchemaTypeDefinition_isComplexType(type):
    return _internals.blpapi_SchemaTypeDefinition_isComplexType(type)

def blpapi_SchemaTypeDefinition_isSimpleType(type):
    return _internals.blpapi_SchemaTypeDefinition_isSimpleType(type)

def blpapi_SchemaTypeDefinition_isEnumerationType(type):
    return _internals.blpapi_SchemaTypeDefinition_isEnumerationType(type)

def blpapi_SchemaTypeDefinition_numElementDefinitions(type):
    return _internals.blpapi_SchemaTypeDefinition_numElementDefinitions(type)

def blpapi_SchemaTypeDefinition_getElementDefinition(type, nameString, name):
    return _internals.blpapi_SchemaTypeDefinition_getElementDefinition(type, nameString, name)

def blpapi_SchemaTypeDefinition_getElementDefinitionAt(type, index):
    return _internals.blpapi_SchemaTypeDefinition_getElementDefinitionAt(type, index)

def blpapi_SchemaTypeDefinition_enumeration(element):
    return _internals.blpapi_SchemaTypeDefinition_enumeration(element)

def blpapi_Request_destroy(request):
    return _internals.blpapi_Request_destroy(request)

def blpapi_Request_elements(request):
    return _internals.blpapi_Request_elements(request)

def blpapi_Request_setPreferredRoute(request, correlationId):
    return _internals.blpapi_Request_setPreferredRoute(request, correlationId)

def blpapi_Request_getRequestId(request):
    return _internals.blpapi_Request_getRequestId(request)

def blpapi_RequestTemplate_release(requestTemplate):
    return _internals.blpapi_RequestTemplate_release(requestTemplate)

def blpapi_Operation_name(operation):
    return _internals.blpapi_Operation_name(operation)

def blpapi_Operation_description(operation):
    return _internals.blpapi_Operation_description(operation)

def blpapi_Operation_requestDefinition(operation):
    return _internals.blpapi_Operation_requestDefinition(operation)

def blpapi_Operation_numResponseDefinitions(operation):
    return _internals.blpapi_Operation_numResponseDefinitions(operation)

def blpapi_Operation_responseDefinition(operation, index):
    return _internals.blpapi_Operation_responseDefinition(operation, index)

def blpapi_Operation_responseDefinitionFromName(operation, name):
    return _internals.blpapi_Operation_responseDefinitionFromName(operation, name)

def blpapi_Service_name(service):
    return _internals.blpapi_Service_name(service)

def blpapi_Service_description(service):
    return _internals.blpapi_Service_description(service)

def blpapi_Service_numOperations(service):
    return _internals.blpapi_Service_numOperations(service)

def blpapi_Service_numEventDefinitions(service):
    return _internals.blpapi_Service_numEventDefinitions(service)

def blpapi_Service_addRef(service):
    return _internals.blpapi_Service_addRef(service)

def blpapi_Service_release(service):
    return _internals.blpapi_Service_release(service)

def blpapi_Service_authorizationServiceName(service):
    return _internals.blpapi_Service_authorizationServiceName(service)

def blpapi_Service_getOperation(service, nameString, name):
    return _internals.blpapi_Service_getOperation(service, nameString, name)

def blpapi_Service_getOperationAt(service, index):
    return _internals.blpapi_Service_getOperationAt(service, index)

def blpapi_Service_getEventDefinition(service, nameString, name):
    return _internals.blpapi_Service_getEventDefinition(service, nameString, name)

def blpapi_Service_getEventDefinitionAt(service, index):
    return _internals.blpapi_Service_getEventDefinitionAt(service, index)

def blpapi_Service_createRequest(service, operation):
    return _internals.blpapi_Service_createRequest(service, operation)

def blpapi_Service_createAuthorizationRequest(service, operation):
    return _internals.blpapi_Service_createAuthorizationRequest(service, operation)

def blpapi_Service_createPublishEvent(service):
    return _internals.blpapi_Service_createPublishEvent(service)

def blpapi_Service_createAdminEvent(service):
    return _internals.blpapi_Service_createAdminEvent(service)

def blpapi_Service_createResponseEvent(service, correlationId):
    return _internals.blpapi_Service_createResponseEvent(service, correlationId)

def blpapi_Message_messageType(message):
    return _internals.blpapi_Message_messageType(message)

def blpapi_Message_topicName(message):
    return _internals.blpapi_Message_topicName(message)

def blpapi_Message_service(message):
    return _internals.blpapi_Message_service(message)

def blpapi_Message_numCorrelationIds(message):
    return _internals.blpapi_Message_numCorrelationIds(message)

def blpapi_Message_correlationId(message, index):
    return _internals.blpapi_Message_correlationId(message, index)

def blpapi_Message_getRequestId(message):
    return _internals.blpapi_Message_getRequestId(message)

def blpapi_Message_elements(message):
    return _internals.blpapi_Message_elements(message)

def blpapi_Message_fragmentType(message):
    return _internals.blpapi_Message_fragmentType(message)

def blpapi_Message_recapType(message):
    return _internals.blpapi_Message_recapType(message)

def blpapi_Message_addRef(message):
    return _internals.blpapi_Message_addRef(message)

def blpapi_Message_release(message):
    return _internals.blpapi_Message_release(message)

def blpapi_Message_timeReceived(message):
    return _internals.blpapi_Message_timeReceived(message)

def blpapi_Event_eventType(event):
    return _internals.blpapi_Event_eventType(event)

def blpapi_Event_release(event):
    return _internals.blpapi_Event_release(event)

def blpapi_EventQueue_create():
    return _internals.blpapi_EventQueue_create()

def blpapi_EventQueue_destroy(eventQueue):
    return _internals.blpapi_EventQueue_destroy(eventQueue)

def blpapi_EventQueue_nextEvent(eventQueue, timeout):
    return _internals.blpapi_EventQueue_nextEvent(eventQueue, timeout)

def blpapi_EventQueue_purge(eventQueue):
    return _internals.blpapi_EventQueue_purge(eventQueue)

def blpapi_EventQueue_tryNextEvent(eventQueue):
    return _internals.blpapi_EventQueue_tryNextEvent(eventQueue)

def blpapi_MessageIterator_create(event):
    return _internals.blpapi_MessageIterator_create(event)

def blpapi_MessageIterator_destroy(iterator):
    return _internals.blpapi_MessageIterator_destroy(iterator)

def blpapi_MessageIterator_next(iterator):
    return _internals.blpapi_MessageIterator_next(iterator)

def blpapi_Identity_release(handle):
    return _internals.blpapi_Identity_release(handle)

def blpapi_Identity_addRef(handle):
    return _internals.blpapi_Identity_addRef(handle)

def blpapi_Identity_hasEntitlements(handle, service, eidElement, entitlementIds, numEntitlements, failedEntitlements, failedEntitlementsCount):
    return _internals.blpapi_Identity_hasEntitlements(handle, service, eidElement, entitlementIds, numEntitlements, failedEntitlements, failedEntitlementsCount)

def blpapi_Identity_isAuthorized(handle, service):
    return _internals.blpapi_Identity_isAuthorized(handle, service)

def blpapi_Identity_getSeatType(handle):
    return _internals.blpapi_Identity_getSeatType(handle)

def blpapi_HighResolutionClock_now():
    return _internals.blpapi_HighResolutionClock_now()

def blpapi_AbstractSession_cancel(session, correlationIds, requestLabel):
    return _internals.blpapi_AbstractSession_cancel(session, correlationIds, requestLabel)

def blpapi_AbstractSession_sendAuthorizationRequest(session, request, identity, correlationId, eventQueue, requestLabel):
    return _internals.blpapi_AbstractSession_sendAuthorizationRequest(session, request, identity, correlationId, eventQueue, requestLabel)

def blpapi_AbstractSession_openService(session, serviceIdentifier):
    return _internals.blpapi_AbstractSession_openService(session, serviceIdentifier)

def blpapi_AbstractSession_openServiceAsync(session, serviceIdentifier, correlationId):
    return _internals.blpapi_AbstractSession_openServiceAsync(session, serviceIdentifier, correlationId)

def blpapi_AbstractSession_generateToken(session, correlationId, eventQueue):
    return _internals.blpapi_AbstractSession_generateToken(session, correlationId, eventQueue)

def blpapi_AbstractSession_generateManualToken(session, correlationId, user, manualIp, eventQueue):
    return _internals.blpapi_AbstractSession_generateManualToken(session, correlationId, user, manualIp, eventQueue)

def blpapi_AbstractSession_getService(session, serviceIdentifier):
    return _internals.blpapi_AbstractSession_getService(session, serviceIdentifier)

def blpapi_AbstractSession_createIdentity(session):
    return _internals.blpapi_AbstractSession_createIdentity(session)

def blpapi_AbstractSession_generateAuthorizedIdentityAsync(session, authOptions, cid):
    return _internals.blpapi_AbstractSession_generateAuthorizedIdentityAsync(session, authOptions, cid)

def blpapi_AbstractSession_getAuthorizedIdentity(session, cid):
    return _internals.blpapi_AbstractSession_getAuthorizedIdentity(session, cid)

def blpapi_Session_start(session):
    return _internals.blpapi_Session_start(session)

def blpapi_Session_startAsync(session):
    return _internals.blpapi_Session_startAsync(session)

def blpapi_Session_stop(session):
    return _internals.blpapi_Session_stop(session)

def blpapi_Session_stopAsync(session):
    return _internals.blpapi_Session_stopAsync(session)

def blpapi_Session_nextEvent(session, timeoutInMilliseconds):
    return _internals.blpapi_Session_nextEvent(session, timeoutInMilliseconds)

def blpapi_Session_tryNextEvent(session):
    return _internals.blpapi_Session_tryNextEvent(session)

def blpapi_Session_subscribe(session, subscriptionList, handle, requestLabel):
    return _internals.blpapi_Session_subscribe(session, subscriptionList, handle, requestLabel)

def blpapi_Session_resubscribe(session, resubscriptionList, requestLabel):
    return _internals.blpapi_Session_resubscribe(session, resubscriptionList, requestLabel)

def blpapi_Session_resubscribeWithId(session, resubscriptionList, resubscriptionId, requestLabel):
    return _internals.blpapi_Session_resubscribeWithId(session, resubscriptionList, resubscriptionId, requestLabel)

def blpapi_Session_unsubscribe(session, unsubscriptionList, requestLabel):
    return _internals.blpapi_Session_unsubscribe(session, unsubscriptionList, requestLabel)

def blpapi_Session_setStatusCorrelationId(session, service, identity, correlationId):
    return _internals.blpapi_Session_setStatusCorrelationId(session, service, identity, correlationId)

def blpapi_Session_sendRequest(session, request, correlationId, identity, eventQueue, requestLabel):
    return _internals.blpapi_Session_sendRequest(session, request, correlationId, identity, eventQueue, requestLabel)

def blpapi_Session_sendRequestTemplate(session, requestTemplate, correlationId):
    return _internals.blpapi_Session_sendRequestTemplate(session, requestTemplate, correlationId)

def blpapi_Session_createSnapshotRequestTemplate(session, subscriptionString, identity, correlationId):
    return _internals.blpapi_Session_createSnapshotRequestTemplate(session, subscriptionString, identity, correlationId)

def blpapi_Session_getAbstractSession(session):
    return _internals.blpapi_Session_getAbstractSession(session)

def blpapi_ResolutionList_extractAttributeFromResolutionSuccess(message, attribute):
    return _internals.blpapi_ResolutionList_extractAttributeFromResolutionSuccess(message, attribute)

def blpapi_ResolutionList_create(_from):
    return _internals.blpapi_ResolutionList_create(_from)

def blpapi_ResolutionList_destroy(list):
    return _internals.blpapi_ResolutionList_destroy(list)

def blpapi_ResolutionList_add(list, topic, correlationId):
    return _internals.blpapi_ResolutionList_add(list, topic, correlationId)

def blpapi_ResolutionList_addFromMessage(list, topic, correlationId):
    return _internals.blpapi_ResolutionList_addFromMessage(list, topic, correlationId)

def blpapi_ResolutionList_addAttribute(list, name):
    return _internals.blpapi_ResolutionList_addAttribute(list, name)

def blpapi_ResolutionList_correlationIdAt(list, index):
    return _internals.blpapi_ResolutionList_correlationIdAt(list, index)

def blpapi_ResolutionList_topicString(list, id):
    return _internals.blpapi_ResolutionList_topicString(list, id)

def blpapi_ResolutionList_topicStringAt(list, index):
    return _internals.blpapi_ResolutionList_topicStringAt(list, index)

def blpapi_ResolutionList_status(list, id):
    return _internals.blpapi_ResolutionList_status(list, id)

def blpapi_ResolutionList_statusAt(list, index):
    return _internals.blpapi_ResolutionList_statusAt(list, index)

def blpapi_ResolutionList_attribute(list, attribute, id):
    return _internals.blpapi_ResolutionList_attribute(list, attribute, id)

def blpapi_ResolutionList_attributeAt(list, attribute, index):
    return _internals.blpapi_ResolutionList_attributeAt(list, attribute, index)

def blpapi_ResolutionList_message(list, id):
    return _internals.blpapi_ResolutionList_message(list, id)

def blpapi_ResolutionList_messageAt(list, index):
    return _internals.blpapi_ResolutionList_messageAt(list, index)

def blpapi_ResolutionList_size(list):
    return _internals.blpapi_ResolutionList_size(list)

def blpapi_TestUtil_createEvent(eventType):
    return _internals.blpapi_TestUtil_createEvent(eventType)

def blpapi_TestUtil_deserializeService(schema, schemaLength):
    return _internals.blpapi_TestUtil_deserializeService(schema, schemaLength)

def blpapi_TestUtil_serializeService(streamWriter, stream, service):
    return _internals.blpapi_TestUtil_serializeService(streamWriter, stream, service)

def blpapi_TestUtil_appendMessage(event, messageType, properties):
    return _internals.blpapi_TestUtil_appendMessage(event, messageType, properties)

def blpapi_TestUtil_createTopic(service, isActive):
    return _internals.blpapi_TestUtil_createTopic(service, isActive)

def blpapi_TestUtil_getAdminMessageDefinition(messageName):
    return _internals.blpapi_TestUtil_getAdminMessageDefinition(messageName)

def blpapi_MessageProperties_create():
    return _internals.blpapi_MessageProperties_create()

def blpapi_MessageProperties_destroy(messageProperties):
    return _internals.blpapi_MessageProperties_destroy(messageProperties)

def blpapi_MessageProperties_copy(src):
    return _internals.blpapi_MessageProperties_copy(src)

def blpapi_MessageProperties_assign(lhs, rhs):
    return _internals.blpapi_MessageProperties_assign(lhs, rhs)

def blpapi_MessageProperties_setCorrelationIds(messageProperties, correlationIds):
    return _internals.blpapi_MessageProperties_setCorrelationIds(messageProperties, correlationIds)

def blpapi_MessageProperties_setRecapType(messageProperties, recap, fragment):
    return _internals.blpapi_MessageProperties_setRecapType(messageProperties, recap, fragment)

def blpapi_MessageProperties_setTimeReceived(messageProperties, timestamp):
    return _internals.blpapi_MessageProperties_setTimeReceived(messageProperties, timestamp)

def blpapi_MessageProperties_setService(messageProperties, service):
    return _internals.blpapi_MessageProperties_setService(messageProperties, service)

def blpapi_MessageProperties_setRequestId(messageProperties, requestId):
    return _internals.blpapi_MessageProperties_setRequestId(messageProperties, requestId)

def blpapi_Topic_create(_from):
    return _internals.blpapi_Topic_create(_from)

def blpapi_Topic_destroy(victim):
    return _internals.blpapi_Topic_destroy(victim)

def blpapi_Topic_compare(lhs, rhs):
    return _internals.blpapi_Topic_compare(lhs, rhs)

def blpapi_Topic_service(topic):
    return _internals.blpapi_Topic_service(topic)

def blpapi_Topic_isActive(topic):
    return _internals.blpapi_Topic_isActive(topic)

def blpapi_TopicList_create(_from):
    return _internals.blpapi_TopicList_create(_from)

def blpapi_TopicList_destroy(list):
    return _internals.blpapi_TopicList_destroy(list)

def blpapi_TopicList_add(list, topic, correlationId):
    return _internals.blpapi_TopicList_add(list, topic, correlationId)

def blpapi_TopicList_addFromMessage(list, topic, correlationId):
    return _internals.blpapi_TopicList_addFromMessage(list, topic, correlationId)

def blpapi_TopicList_correlationIdAt(list, index):
    return _internals.blpapi_TopicList_correlationIdAt(list, index)

def blpapi_TopicList_topicString(list, id):
    return _internals.blpapi_TopicList_topicString(list, id)

def blpapi_TopicList_topicStringAt(list, index):
    return _internals.blpapi_TopicList_topicStringAt(list, index)

def blpapi_TopicList_status(list, id):
    return _internals.blpapi_TopicList_status(list, id)

def blpapi_TopicList_statusAt(list, index):
    return _internals.blpapi_TopicList_statusAt(list, index)

def blpapi_TopicList_message(list, id):
    return _internals.blpapi_TopicList_message(list, id)

def blpapi_TopicList_messageAt(list, index):
    return _internals.blpapi_TopicList_messageAt(list, index)

def blpapi_TopicList_size(list):
    return _internals.blpapi_TopicList_size(list)

def blpapi_ProviderSession_create(parameters, handler, dispatcher, userData):
    return _internals.blpapi_ProviderSession_create(parameters, handler, dispatcher, userData)

def blpapi_ProviderSession_destroy(session):
    return _internals.blpapi_ProviderSession_destroy(session)

def blpapi_ProviderSession_start(session):
    return _internals.blpapi_ProviderSession_start(session)

def blpapi_ProviderSession_startAsync(session):
    return _internals.blpapi_ProviderSession_startAsync(session)

def blpapi_ProviderSession_stop(session):
    return _internals.blpapi_ProviderSession_stop(session)

def blpapi_ProviderSession_stopAsync(session):
    return _internals.blpapi_ProviderSession_stopAsync(session)

def blpapi_ProviderSession_nextEvent(session, timeoutInMilliseconds):
    return _internals.blpapi_ProviderSession_nextEvent(session, timeoutInMilliseconds)

def blpapi_ProviderSession_tryNextEvent(session):
    return _internals.blpapi_ProviderSession_tryNextEvent(session)

def blpapi_ProviderSession_registerService(session, serviceName, identity, registrationOptions):
    return _internals.blpapi_ProviderSession_registerService(session, serviceName, identity, registrationOptions)

def blpapi_ProviderSession_activateSubServiceCodeRange(session, serviceName, begin, end, priority):
    return _internals.blpapi_ProviderSession_activateSubServiceCodeRange(session, serviceName, begin, end, priority)

def blpapi_ProviderSession_deactivateSubServiceCodeRange(session, serviceName, begin, end):
    return _internals.blpapi_ProviderSession_deactivateSubServiceCodeRange(session, serviceName, begin, end)

def blpapi_ProviderSession_registerServiceAsync(session, serviceName, identity, correlationId, registrationOptions):
    return _internals.blpapi_ProviderSession_registerServiceAsync(session, serviceName, identity, correlationId, registrationOptions)

def blpapi_ProviderSession_deregisterService(session, serviceName):
    return _internals.blpapi_ProviderSession_deregisterService(session, serviceName)

def blpapi_ProviderSession_resolve(session, resolutionList, resolveMode, identity):
    return _internals.blpapi_ProviderSession_resolve(session, resolutionList, resolveMode, identity)

def blpapi_ProviderSession_resolveAsync(session, resolutionList, resolveMode, identity):
    return _internals.blpapi_ProviderSession_resolveAsync(session, resolutionList, resolveMode, identity)

def blpapi_ProviderSession_createTopics(session, topicList, resolveMode, identity):
    return _internals.blpapi_ProviderSession_createTopics(session, topicList, resolveMode, identity)

def blpapi_ProviderSession_createTopicsAsync(session, topicList, resolveMode, identity):
    return _internals.blpapi_ProviderSession_createTopicsAsync(session, topicList, resolveMode, identity)

def blpapi_ProviderSession_getTopic(session, message):
    return _internals.blpapi_ProviderSession_getTopic(session, message)

def blpapi_ProviderSession_createTopic(session, message):
    return _internals.blpapi_ProviderSession_createTopic(session, message)

def blpapi_ProviderSession_createServiceStatusTopic(session, service):
    return _internals.blpapi_ProviderSession_createServiceStatusTopic(session, service)

def blpapi_ProviderSession_deleteTopics(session, topics, numTopics):
    return _internals.blpapi_ProviderSession_deleteTopics(session, topics, numTopics)

def blpapi_ProviderSession_terminateSubscriptionsOnTopics(session, topics, numTopics, message):
    return _internals.blpapi_ProviderSession_terminateSubscriptionsOnTopics(session, topics, numTopics, message)

def blpapi_ProviderSession_publish(session, event):
    return _internals.blpapi_ProviderSession_publish(session, event)

def blpapi_ProviderSession_sendResponse(session, event, isPartialResponse):
    return _internals.blpapi_ProviderSession_sendResponse(session, event, isPartialResponse)

def blpapi_ProviderSession_getAbstractSession(session):
    return _internals.blpapi_ProviderSession_getAbstractSession(session)

def blpapi_ProviderSession_flushPublishedEvents(session, timeoutMsecs):
    return _internals.blpapi_ProviderSession_flushPublishedEvents(session, timeoutMsecs)

def blpapi_ServiceRegistrationOptions_create():
    return _internals.blpapi_ServiceRegistrationOptions_create()

def blpapi_ServiceRegistrationOptions_duplicate(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_duplicate(parameters)

def blpapi_ServiceRegistrationOptions_destroy(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_destroy(parameters)

def blpapi_ServiceRegistrationOptions_copy(lhs, rhs):
    return _internals.blpapi_ServiceRegistrationOptions_copy(lhs, rhs)

def blpapi_ServiceRegistrationOptions_addActiveSubServiceCodeRange(parameters, start, end, priority):
    return _internals.blpapi_ServiceRegistrationOptions_addActiveSubServiceCodeRange(parameters, start, end, priority)

def blpapi_ServiceRegistrationOptions_removeAllActiveSubServiceCodeRanges(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_removeAllActiveSubServiceCodeRanges(parameters)

def blpapi_ServiceRegistrationOptions_setGroupId(parameters, groupId):
    return _internals.blpapi_ServiceRegistrationOptions_setGroupId(parameters, groupId)

def blpapi_ServiceRegistrationOptions_setServicePriority(parameters, priority):
    return _internals.blpapi_ServiceRegistrationOptions_setServicePriority(parameters, priority)

def blpapi_ServiceRegistrationOptions_setPartsToRegister(parameters, parts):
    return _internals.blpapi_ServiceRegistrationOptions_setPartsToRegister(parameters, parts)

def blpapi_ServiceRegistrationOptions_getGroupId(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_getGroupId(parameters)

def blpapi_ServiceRegistrationOptions_getServicePriority(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_getServicePriority(parameters)

def blpapi_ServiceRegistrationOptions_getPartsToRegister(parameters):
    return _internals.blpapi_ServiceRegistrationOptions_getPartsToRegister(parameters)

def blpapi_ZfpUtil_getOptionsForLeasedLines(sessionOptions, tlsOptions, remote):
    return _internals.blpapi_ZfpUtil_getOptionsForLeasedLines(sessionOptions, tlsOptions, remote)


